# -*- coding: utf-8 -*-
# 各地图配置: 楼层(r6calls号)/中文名/房间中文对照/包点/包点选择器
# 房间条目: (r6calls名, 中文, 英文, kind, k, 色型)  色型 gold(目标)/corr(走廊楼梯)/room/ext(室外)
MAPCFG = {}

MAPCFG["bank"] = {
 "mapcn":"银行","mapen":"Bank",
 "order":["3","2","1","0"], "default":"1",
 "names":{"3":"屋顶","2":"二楼","1":"一楼","0":"地下室"},
 "en":{"3":"ROOF","2":"2F","1":"1F","0":"B"},
 "notes":{"3":"屋顶层 · 室外","2":"CEO办公室 + 高管室","1":"柜员 + 档案 + 开放区","0":"金库 + 储物间 + 监控"},
 "sites":[{"id":"1","f":"2","n":"① CEO·高管"},{"id":"2","f":"1","n":"② 开放区·厨房"},
          {"id":"3","f":"1","n":"③ 柜员·档案"},{"id":"4","f":"0","n":"④ 储物间·监控"}],
 "bombs":{"2":["1A","1B"],"1":["2A","2B","3A","3B"],"0":["4A","4B"]},
 "rooms":{
  "0":[("Lockers","储物间","Lockers","目标","obj","gold"),("CCTV","监控室","CCTV","目标","obj","gold"),
       ("Vault","金库","Vault","","room","room"),("Gold","黄金库","Gold","","room","room"),
       ("Cash","现金库","Cash","","room","room"),("Vault Entrance","金库入口","Vault Ent.","","room","room"),
       ("Vault Lobby","金库大厅","Vault Lobby","","room","room"),("Lockers Hallway","储物间走廊","Lockers Hall","","room","corr"),
       ("Red Hallway","红色走廊","Red Hallway","","room","corr"),("Server","服务器室","Server","","room","room"),
       ("Tunnel","隧道","Tunnel","","room","room"),("Garage","车库","Garage","","room","room"),
       ("Red Truck","红卡车","Red Truck","","room","room"),("Dock","装卸区","Dock","","room","room"),
       ("Main Stairs","主楼梯","Main Stairs","","room","corr"),("Blue Stairs","蓝楼梯","Blue Stairs","","room","corr"),
       ("Elevators","电梯","Elevators","","room","corr")],
  "1":[("Tellers","柜员区","Tellers","目标","obj","gold"),("Archives","档案室","Archives","目标","obj","gold"),
       ("Open Space","开放区","Open Space","目标","obj","gold"),("Kitchen","厨房","Kitchen","目标","obj","gold"),
       ("Tellers Office","柜员办公室","Tellers Office","","room","room"),("Lobby","大堂","Lobby","","room","room"),
       ("Admin","行政室","Admin","","room","room"),("Loan","贷款室","Loan","","room","room"),
       ("Electrical","电气室","Electrical","","room","room"),("Square","广场厅","Square","","room","room"),
       ("Printer","打印室","Printer","","room","room"),("ATMs","取款机厅","ATMs","","room","room"),
       ("Open Space Hallway","开放区走廊","O.S.Hallway","","room","corr"),("Lobby Stairs","大堂楼梯","Lobby Stairs","","room","corr"),
       ("Square Stairs","广场楼梯","Square Stairs","","room","corr"),("Main Stairs","主楼梯","Main Stairs","","room","corr"),
       ("Elevators","电梯","Elevators","","room","corr"),("Garage Roof","车库顶","Garage Roof","室外","ext","ext")],
  "2":[("CEO","CEO办公室","CEO","目标","obj","gold"),("Exec","高管室","Exec","目标","obj","gold"),
       ("Front Desk","前台","Front Desk","","room","room"),("Meeting","会议室","Meeting","","room","room"),
       ("Stock","证券室","Stock","","room","room"),("Top Square","广场上层","Top Square","","room","room"),
       ("Janitor","清洁间","Janitor","","room","room"),("Banana","香蕉拐角","Banana","","room","room"),
       ("Lobby","大堂","Lobby","","room","room"),("Loan","贷款室","Loan","","room","room"),
       ("ATMs","取款机厅","ATMs","","room","room"),("Exec Hallway","高管走廊","Exec Hall","","room","corr"),
       ("Meeting Hallway","会议室走廊","Meeting Hall","","room","corr"),("Stock Hallway","证券室走廊","Stock Hall","","room","corr"),
       ("Lobby Stairs","大堂楼梯","Lobby Stairs","","room","corr"),("Square Stairs","广场楼梯","Square Stairs","","room","corr"),
       ("Main Stairs","主楼梯","Main Stairs","","room","corr"),("Elevators","电梯","Elevators","","room","corr"),
       ("Terrace","露台","Terrace","室外","ext","ext"),("Garage Roof","车库顶","Garage Roof","室外","ext","ext")],
  "3":[("High Roof","高屋顶","High Roof","室外","ext","ext"),("Low Roof","低屋顶","Low Roof","室外","ext","ext"),
       ("Terrace","露台","Terrace","室外","ext","ext"),("Garage Roof","车库顶","Garage Roof","室外","ext","ext")],
 },
}

MAPCFG["oregon"] = {
 "mapcn":"俄勒冈","mapen":"Oregon",
 "order":["3","2","1","0"], "default":"1",
 "names":{"3":"屋顶","2":"二楼","1":"一楼","0":"地下室"},
 "en":{"3":"ROOF","2":"2F","1":"1F","0":"B"},
 "notes":{"3":"屋顶层 · 室外","2":"儿童房 + 主卧 + 阁楼","1":"厨房 + 会议室 + 餐厅","0":"冷冻库 + 地下走廊"},
 "sites":[{"id":"1","f":"2","n":"① 儿童房·主卧"},{"id":"2","f":"1","n":"② 厨房·餐厅"},
          {"id":"3","f":"1","n":"③ 会议室"},{"id":"4","f":"0","n":"④ 冷冻库·走廊"}],
 "bombs":{"2":["1A","1B"],"1":["2A","2B","3A","3B"],"0":["4A","4B"]},
 "rooms":{
  "0":[("Freezer","冷冻库","Freezer","目标","obj","gold"),("Basement Corridor","地下走廊","B.Corridor","目标","obj","gold"),
       ("Storage","储藏室","Storage","","room","room"),("Laundry","洗衣房","Laundry","","room","room"),
       ("Closet","壁橱","Closet","","room","room"),("Supply","补给室","Supply","","room","room"),
       ("Blue","蓝色房","Blue","","room","room"),("Pillar","柱厅","Pillar","","room","room"),
       ("Electric","电气室","Electric","","room","room"),("Bunker","地堡","Bunker","","room","room"),
       ("Freezer Stairs","冷冻库楼梯","Freezer Stairs","","room","corr"),("Laundry Stairs","洗衣房楼梯","Laundry Stairs","","room","corr"),
       ("Tower Stairs","塔楼楼梯","Tower Stairs","","room","corr")],
  "1":[("Kitchen","厨房","Kitchen","目标","obj","gold"),("Dining","餐厅","Dining","目标","obj","gold"),
       ("Meeting","会议室","Meeting","目标","obj","gold"),("Classroom","教室","Classroom","","room","room"),
       ("Lobby","大堂","Lobby","","room","room"),("Showers","淋浴间","Showers","","room","room"),
       ("Security","保安室","Security","","room","room"),("Split","分岔厅","Split","","room","room"),
       ("Stage","舞台","Stage","","room","room"),("Tower","塔楼","Tower","","room","room"),
       ("Garage","车库","Garage","","room","room"),("Small Tower","小塔楼","Small Tower","","room","room"),
       ("Shower Corridor","淋浴走廊","Shower Corr.","","room","corr"),("Security Corridor","保安走廊","Security Corr.","","room","corr"),
       ("Kitchen Corridor","厨房走廊","Kitchen Corr.","","room","corr"),("White Stairs","白楼梯","White Stairs","","room","corr"),
       ("Armory Stairs","军械库楼梯","Armory Stairs","","room","corr"),("TowerStairs","塔楼楼梯","Tower Stairs","","room","corr"),
       ("SmallStairs","小楼梯","Small Stairs","","room","corr")],
  "2":[("Kids","儿童房","Kids","目标","obj","gold"),("Master","主卧","Master","目标","obj","gold"),
       ("Attic","阁楼","Attic","","room","room"),("Low Attic","下阁楼","Low Attic","","room","room"),
       ("Middle","中厅","Middle","","room","room"),("Trophy","奖杯室","Trophy","","room","room"),
       ("Office","办公室","Office","","room","room"),("Armory","军械库","Armory","","room","room"),
       ("Gaming","游戏室","Gaming","","room","room"),("Dorm","宿舍","Dorm","","room","room"),
       ("Walk In","步入衣柜","Walk In","","room","room"),("Small Tower","小塔楼","Small Tower","","room","room"),
       ("Armory Corridor","军械库走廊","Armory Corr.","","room","corr"),("White Stairs","白楼梯","White Stairs","","room","corr"),
       ("Armory Stairs","军械库楼梯","Armory Stairs","","room","corr"),("TowerStairs","塔楼楼梯","Tower Stairs","","room","corr"),
       ("Balcony","阳台","Balcony","室外","ext","ext")],
  "3":[("Tower Roof","塔楼顶","Tower Roof","室外","ext","ext"),("Attic Roof","阁楼顶","Attic Roof","室外","ext","ext"),
       ("Meeting Roof","会议室顶","Meeting Roof","室外","ext","ext"),("Armory Roof","军械库顶","Armory Roof","室外","ext","ext"),
       ("Master Roof","主卧顶","Master Roof","室外","ext","ext"),("Kids Roof","儿童房顶","Kids Roof","室外","ext","ext"),
       ("Dorms Roof","宿舍顶","Dorms Roof","室外","ext","ext"),("Dining Roof","餐厅顶","Dining Roof","室外","ext","ext"),
       ("Small Tower Roof","小塔楼顶","Small Tower Roof","室外","ext","ext"),("Cat Walk","猫道","Cat Walk","室外","ext","ext")],
 },
}

MAPCFG["border"] = {
 "mapcn":"边境","mapen":"Border",
 "order":["3","2","1"], "default":"1",
 "names":{"3":"屋顶","2":"二楼","1":"一楼"},
 "en":{"3":"ROOF","2":"2F","1":"1F"},
 "notes":{"3":"屋顶层 · 室外","2":"军械库 + 档案室 + 办公室","1":"海关 + 补给 + 工作间 + 柜台"},
 "sites":[{"id":"1","f":"1","n":"① 补给·海关"},{"id":"2","f":"1","n":"② 工作间·通风"},
          {"id":"3","f":"1","n":"③ 洗手间·柜台"},{"id":"4","f":"2","n":"④ 军械库·档案"}],
 "bombs":{"1":["1A","1B","2A","2B","3A","3B"],"2":["4A","4B"]},
 "rooms":{
  "1":[("Supply","补给室","Supply","目标","obj","gold"),("Customs","海关","Customs","目标","obj","gold"),
       ("Workshop","工作间","Workshop","目标","obj","gold"),("Ventilation","通风室","Ventilation","目标","obj","gold"),
       ("Bathroom","洗手间","Bathroom","目标","obj","gold"),("Tellers","柜台","Tellers","目标","obj","gold"),
       ("Detention","拘留室","Detention","","room","room"),("Customs Desk","海关台","Customs Desk","","room","room"),
       ("Waiting","等候区","Waiting","","room","room"),("Server","服务器室","Server","","room","room"),
       ("Passport","护照处","Passport","","room","room"),("Lobby","大堂","Lobby","","room","room"),
       ("Supply Corridor","补给走廊","Supply Corr.","","room","corr"),("Ventilation Hallway","通风走廊","Vent. Hall","","room","corr"),
       ("Bathroom Hallway","洗手间走廊","Bath Hall","","room","corr"),("Main Stairs","主楼梯","Main Stairs","","room","corr"),
       ("East Stairs","东楼梯","East Stairs","","room","corr")],
  "2":[("Armory","军械库","Armory","目标","obj","gold"),("Archives","档案室","Archives","目标","obj","gold"),
       ("Armory Desk","军械库台","Armory Desk","","room","room"),("CCTV","监控室","CCTV","","room","room"),
       ("Cafeteria","食堂","Cafeteria","","room","room"),("Fountain","喷泉厅","Fountain","","room","room"),
       ("Offices","办公室","Offices","","room","room"),("Waiting","等候区","Waiting","","room","room"),
       ("Sandwich","三明治角","Sandwich","","room","room"),("Offices Hallway","办公室走廊","Offices Hall","","room","corr"),
       ("Main Stairs","主楼梯","Main Stairs","","room","corr"),("East Stairs","东楼梯","East Stairs","","room","corr")],
  "3":[("Roof","屋顶","Roof","室外","ext","ext"),("Balcony Stairs","阳台楼梯","Balcony Stairs","室外","ext","ext")],
 },
}

MAPCFG["coastline"] = {
 "mapcn":"海岸线","mapen":"Coastline",
 "order":["3","2","1"], "default":"2",
 "names":{"3":"屋顶","2":"二楼","1":"一楼"},
 "en":{"3":"ROOF","2":"2F","1":"1F"},
 "notes":{"3":"屋顶层 · 室外","2":"水烟房 + 顶层套房 + VIP","1":"蓝吧 + 日出房 + 厨房"},
 "sites":[{"id":"1","f":"2","n":"① 水烟·台球"},{"id":"2","f":"2","n":"② 套房·电视"},
          {"id":"3","f":"1","n":"③ 厨房·补给"},{"id":"4","f":"1","n":"④ 蓝吧·日出"}],
 "bombs":{"2":["1A","1B","2A","2B"],"1":["3A","3B","4A","4B"]},
 "rooms":{
  "1":[("Kitchen","厨房","Kitchen","目标","obj","gold"),("Supply","补给室","Supply","目标","obj","gold"),
       ("Blue Bar","蓝吧","Blue Bar","目标","obj","gold"),("Sunrise","日出房","Sunrise","目标","obj","gold"),
       ("Delivery","送货区","Delivery","","room","room"),("Toilets","洗手间","Toilets","","room","room"),
       ("Lobby","大堂","Lobby","","room","room"),("Security","保安室","Security","","room","room"),
       ("Sun","阳光房","Sun","","room","room"),("Library","图书室","Library","","room","room"),
       ("Cantina","餐吧","Cantina","","room","room"),("Reception","前台","Reception","","room","room"),
       ("Kitchen Hallway","厨房走廊","Kitchen Hall","","room","corr"),("Sunrise Entrance","日出入口","Sunrise Ent.","","room","corr"),
       ("Sunrise Hallway","日出走廊","Sunrise Hall","","room","corr"),("White Stairs","白楼梯","White Stairs","","room","corr"),
       ("Blue Stairs","蓝楼梯","Blue Stairs","","room","corr"),("Courtyard","中庭","Courtyard","室外","ext","ext"),
       ("Promenade","步道","Promenade","室外","ext","ext"),("Terrace","露台","Terrace","室外","ext","ext")],
  "2":[("Hookah","水烟房","Hookah","目标","obj","gold"),("Pool Table","台球室","Pool Table","目标","obj","gold"),
       ("Penthouse","顶层套房","Penthouse","目标","obj","gold"),("TV","电视室","TV","目标","obj","gold"),
       ("VIP","VIP室","VIP","","room","room"),("Pool Bar","泳池吧","Pool Bar","","room","room"),
       ("Luggage","行李房","Luggage","","room","room"),("Aqua","水族房","Aqua","","room","room"),
       ("Guitars","吉他室","Guitars","","room","room"),("Bathroom","洗手间","Bathroom","","room","room"),
       ("VIP Hallway","VIP走廊","VIP Hall","","room","corr"),("TV Hallway","电视走廊","TV Hall","","room","corr"),
       ("Hookah Hallway","水烟走廊","Hookah Hall","","room","corr"),("White Stairs","白楼梯","White Stairs","","room","corr"),
       ("Blue Stairs","蓝楼梯","Blue Stairs","","room","corr"),("Roof Drop","屋顶下沉口","Roof Drop","","room","room"),
       ("Courtyard","中庭","Courtyard","室外","ext","ext"),("Promenade","步道","Promenade","室外","ext","ext")],
  "3":[("Roof","屋顶","Roof","室外","ext","ext"),("Roof Drop","屋顶下沉口","Roof Drop","室外","ext","ext")],
 },
}

MAPCFG["consulate"] = {
 "mapcn":"领事馆","mapen":"Consulate",
 "order":["3","2","1","0"], "default":"1",
 "names":{"3":"屋顶","2":"二楼","1":"一楼","0":"地下室"},
 "en":{"3":"ROOF","2":"2F","1":"1F","0":"B"},
 "notes":{"3":"屋顶层 · 室外","2":"领事办公室 + 会议室","1":"钢琴室 + 展览 + 柜台","0":"车库 + 服务器 + 厨房"},
 "sites":[{"id":"1","f":"2","n":"① 领事办·会议"},{"id":"2","f":"1","n":"② 钢琴·展览"},
          {"id":"3","f":"1","n":"③ 休息室·服务器"},{"id":"4","f":"0","n":"④ 车库·厨房"}],
 "bombs":{"2":["1A","1B"],"1":["2A","2B","3A"],"0":["4A","4B","3B"]},
 "rooms":{
  "0":[("Garage","车库","Garage","目标","obj","gold"),("Kitchen","厨房","Kitchen","目标","obj","gold"),
       ("Servers","服务器室","Servers","目标","obj","gold"),("Coffee","咖啡角","Coffee","","room","room"),
       ("CCTV","监控室","CCTV","","room","room"),("Banana","香蕉拐角","Banana","","room","room"),
       ("Lockers","储物间","Lockers","","room","room"),("Electrical","电气室","Electrical","","room","room"),
       ("Storage","储藏室","Storage","","room","room"),("Pillar","柱厅","Pillar","","room","room"),
       ("Construction","施工区","Construction","","room","room"),("Delivery","送货区","Delivery","","room","room"),
       ("ServerHallway","服务器走廊","Server Hall","","room","corr")],
  "1":[("Piano","钢琴室","Piano","目标","obj","gold"),("Expo","展览厅","Expo","目标","obj","gold"),
       ("Lounge","休息室","Lounge","目标","obj","gold"),("Statue","雕像厅","Statue","","room","room"),
       ("Tellers","柜台","Tellers","","room","room"),("Visa","签证处","Visa","","room","room"),
       ("Emergency","应急室","Emergency","","room","room"),("Closet","壁橱","Closet","","room","room"),
       ("Lobby","大堂","Lobby","","room","room"),("Gumball","口香糖机","Gumball","","room","room"),
       ("Tellers Hallway","柜台走廊","Tellers Hall","","room","corr"),("Visa Hallway","签证走廊","Visa Hall","","room","corr"),
       ("Visa Entrance","签证入口","Visa Ent.","","room","corr"),("Piano Hallway","钢琴走廊","Piano Hall","","room","corr"),
       ("Yellow Stairs","黄楼梯","Yellow Stairs","","room","corr")],
  "2":[("CEO","领事办公室","Consul Office","目标","obj","gold"),("Meeting","会议室","Meeting","目标","obj","gold"),
       ("CEO Side","领事侧室","CEO Side","","room","room"),("Break","休息室","Break","","room","room"),
       ("Catering","餐饮室","Catering","","room","room"),("Copy","复印室","Copy","","room","room"),
       ("Soda","汽水角","Soda","","room","room"),("Admin","行政室","Admin","","room","room"),
       ("Front Office","前厅","Front Office","","room","room"),("Secretary","秘书室","Secretary","","room","room"),
       ("Bathroom","洗手间","Bathroom","","room","room"),("Long Desk","长桌厅","Long Desk","","room","room"),
       ("Meeting Hallway","会议走廊","Meeting Hall","","room","corr"),("Break Hallway","休息走廊","Break Hall","","room","corr"),
       ("Consule Hallway","领事走廊","Consul Hall","","room","corr"),("ManagerHallway","经理走廊","Manager Hall","","room","corr"),
       ("Balcony","阳台","Balcony","室外","ext","ext")],
  "3":[("Garage Roof","车库顶","Garage Roof","室外","ext","ext"),("Emergency Roof","应急顶","Emergency Roof","室外","ext","ext")],
 },
}

MAPCFG["villa"] = {
 "mapcn":"别墅","mapen":"Villa",
 "order":["3","2","1","0"], "default":"2",
 "names":{"3":"屋顶","2":"二楼","1":"一楼","0":"地下室"},
 "en":{"3":"ROOF","2":"2F","1":"1F","0":"B"},
 "notes":{"3":"屋顶层 · 室外","2":"飞行家 + 奖杯室 + 雕像厅","1":"画廊 + 图书室 + 厨房 + 餐厅","0":"酒窖 + 地穴 + 车库"},
 "sites":[{"id":"1","f":"2","n":"① 飞行家·书房"},{"id":"2","f":"2","n":"② 奖杯·雕像"},
          {"id":"3","f":"1","n":"③ 画廊·图书室"},{"id":"4","f":"1","n":"④ 厨房·餐厅"}],
 "bombs":{"2":["1A","1B","2A","2B"],"1":["3A","3B","4A","4B"]},
 "rooms":{
  "0":[("Wine","酒窖","Wine","","room","room"),("Tasting","品酒室","Tasting","","room","room"),
       ("Art","艺术室","Art","","room","room"),("Arch","拱厅","Arch","","room","room"),
       ("Office","办公室","Office","","room","room"),("Garage","车库","Garage","","room","room"),
       ("Crypt","地穴","Crypt","","room","room"),("Crypt Tunnel","地穴隧道","Crypt Tunnel","","room","corr"),
       ("Cellar Tunnel","酒窖隧道","Cellar Tunnel","","room","corr"),("Red Stairs","红楼梯","Red Stairs","","room","corr"),
       ("Back Stairs","后楼梯","Back Stairs","","room","corr"),("Pantry Stairs","储藏室楼梯","Pantry Stairs","","room","corr")],
  "1":[("Gallery","画廊","Gallery","目标","obj","gold"),("Library","图书室","Library","目标","obj","gold"),
       ("Kitchen","厨房","Kitchen","目标","obj","gold"),("Dining","餐厅","Dining","目标","obj","gold"),
       ("Living","客厅","Living","","room","room"),("Piano","钢琴室","Piano","","room","room"),
       ("China","瓷器室","China","","room","room"),("Pantry","储藏室","Pantry","","room","room"),
       ("Memorial","纪念室","Memorial","","room","room"),("Mudroom","玄关","Mudroom","","room","room"),
       ("Laundry","洗衣房","Laundry","","room","room"),("Toilet","洗手间","Toilet","","room","room"),
       ("Studio","工作室","Studio","","room","room"),("Bicycle","自行车房","Bicycle","","room","room"),
       ("Greenhouse","温室","Greenhouse","","room","room"),("Main","主厅","Main","","room","room"),
       ("Front Entrance","前门","Front Ent.","","room","corr"),("Back Hallway","后走廊","Back Hall","","room","corr"),
       ("Living Hallway","客厅走廊","Living Hall","","room","corr"),("Piano Hallway","钢琴走廊","Piano Hall","","room","corr"),
       ("Astro Stairs","星空楼梯","Astro Stairs","","room","corr"),("Red Stairs","红楼梯","Red Stairs","","room","corr"),
       ("Brown Stairs","棕楼梯","Brown Stairs","","room","corr"),("Terrace","露台","Terrace","室外","ext","ext")],
  "2":[("Aviator","飞行家","Aviator","目标","obj","gold"),("Study","书房","Study","目标","obj","gold"),
       ("Trophy","奖杯室","Trophy","目标","obj","gold"),("Statue","雕像厅","Statue","目标","obj","gold"),
       ("Master","主卧","Master","","room","room"),("Astro","星空房","Astro","","room","room"),
       ("Bathroom","洗手间","Bathroom","","room","room"),("Closet","壁橱","Closet","","room","room"),
       ("Gaming","游戏室","Gaming","","room","room"),("Bar","吧台","Bar","","room","room"),
       ("Vault","金库","Vault","","room","room"),("Skull","骷髅室","Skull","","room","room"),
       ("Ninety","九十号","Ninety","","room","room"),("Ninety Corner","九十号角","Ninety Corner","","room","room"),
       ("TrophyEntrance","奖杯入口","Trophy Ent.","","room","corr"),("Landing","楼梯平台","Landing","","room","corr"),
       ("Astro Stairs","星空楼梯","Astro Stairs","","room","corr"),("Red Stairs","红楼梯","Red Stairs","","room","corr"),
       ("Brown Stairs","棕楼梯","Brown Stairs","","room","corr")],
  "3":[("Roof","屋顶","Roof","室外","ext","ext"),("Terrace","露台","Terrace","室外","ext","ext")],
 },
}

MAPCFG["chalet"] = {
 "mapcn":"木屋","mapen":"Chalet",
 "order":["3","2","1","0"], "default":"1",
 "names":{"3":"屋顶","2":"二楼","1":"一楼","0":"地下室"},
 "en":{"3":"ROOF","2":"2F","1":"1F","0":"B"},
 "notes":{"3":"屋顶层 · 室外","2":"主卧 + 办公室 + 图书室","1":"游戏室 + 吧台 + 餐厅 + 厨房","0":"酒窖 + 蓝房 + 车库"},
 "sites":[{"id":"1","f":"2","n":"① 主卧·办公室"},{"id":"2","f":"1","n":"② 游戏室·吧台"},
          {"id":"3","f":"1","n":"③ 餐厅·厨房"},{"id":"4","f":"0","n":"④ 酒窖·蓝房"}],
 "bombs":{"2":["1A","1B"],"1":["2A","2B","3A","3B"],"0":["4A","4B"]},
 "rooms":{
  "0":[("Wine","酒窖","Wine","目标","obj","gold"),("Blue","蓝房","Blue","目标","obj","gold"),
       ("Garage","车库","Garage","","room","room"),("Car Garage","大车库","Car Garage","","room","room"),
       ("Storage","储藏室","Storage","","room","room"),("Basement Hallway","地下走廊","B.Hallway","","room","corr"),
       ("Blue Stairs","蓝楼梯","Blue Stairs","","room","corr"),("Garage Stairs","车库楼梯","Garage Stairs","","room","corr"),
       ("Main Stairs","主楼梯","Main Stairs","","room","corr"),("CarGarageEntrance","车库入口","Car Garage Ent.","","room","corr")],
  "1":[("Gaming","游戏室","Gaming","目标","obj","gold"),("Bar","吧台","Bar","目标","obj","gold"),
       ("Dining","餐厅","Dining","目标","obj","gold"),("Kitchen","厨房","Kitchen","目标","obj","gold"),
       ("Bar Stock","吧台储藏","Bar Stock","","room","room"),("Fireplace","壁炉厅","Fireplace","","room","room"),
       ("Mudroom","玄关","Mudroom","","room","room"),("Trophy","奖杯室","Trophy","","room","room"),
       ("Main","主厅","Main","","room","room"),("Dining Hallway","餐厅走廊","Dining Hall","","room","corr"),
       ("Kitchen Hallway","厨房走廊","Kitchen Hall","","room","corr"),("Bar Hallway","吧台走廊","Bar Hall","","room","corr"),
       ("Gaming Hallway","游戏室走廊","Gaming Hall","","room","corr"),("Fireplace Stairs","壁炉楼梯","Fireplace Stairs","","room","corr"),
       ("Trophy Stairs","奖杯楼梯","Trophy Stairs","","room","corr"),("Backyard Stairs","后院楼梯","Backyard Stairs","","room","corr")],
  "2":[("Master","主卧","Master","目标","obj","gold"),("Office","办公室","Office","目标","obj","gold"),
       ("Piano","钢琴室","Piano","","room","room"),("Solarium","阳光房","Solarium","","room","room"),
       ("Bathroom","洗手间","Bathroom","","room","room"),("Closet","壁橱","Closet","","room","room"),
       ("Mezzanine","夹层","Mezzanine","","room","room"),("Library","图书室","Library","","room","room"),
       ("Library Entrance","图书室入口","Library Ent.","","room","corr"),("Library Hallway","图书室走廊","Library Hall","","room","corr"),
       ("Trophy Stairs","奖杯楼梯","Trophy Stairs","","room","corr")],
  "3":[("Roof","屋顶","Roof","室外","ext","ext"),("Backyard","后院","Backyard","室外","ext","ext")],
 },
}

MAPCFG["labs"] = {
 "mapcn":"实验室","mapen":"Nighthaven Labs",
 "order":["3","2","1","0"], "default":"1",
 "names":{"3":"屋顶","2":"二楼","1":"一楼","0":"地下室"},
 "en":{"3":"ROOF","2":"2F","1":"1F","0":"B"},
 "notes":{"3":"屋顶层 · 直升机坪","2":"指挥室 + 服务器 + 会议室","1":"厨房 + 食堂 + 控制室 + 储藏","0":"外骨骼室 + 装配室 + 纳米室"},
 "sites":[{"id":"1","f":"2","n":"① 指挥·服务器"},{"id":"2","f":"1","n":"② 厨房·食堂"},
          {"id":"3","f":"1","n":"③ 控制室·储藏"},{"id":"4","f":"0","n":"④ 外骨骼·装配"}],
 "bombs":{"2":["1A","1B"],"1":["2A","2B","3A","3B"],"0":["4A","4B"]},
 "rooms":{
  "0":[("Exo","外骨骼室","Exo","目标","obj","gold"),("Animus","阿尼姆斯","Animus","目标","obj","gold"),
       ("Assembly","装配室","Assembly","","room","room"),("Nano","纳米室","Nano","","room","room"),
       ("Tank","罐体室","Tank","","room","room"),("Cargo","货舱","Cargo","","room","room"),
       ("Emergency","应急室","Emergency","","room","room"),("AssemblyDelivery","装配送货","Assembly Del.","","room","room"),
       ("AnimusDelivery","阿尼姆斯送货","Animus Del.","","room","room"),("Nano Hallway","纳米走廊","Nano Hall","","room","corr"),
       ("Exo Hallway","外骨骼走廊","Exo Hall","","room","corr"),("Cargo Stairs","货舱楼梯","Cargo Stairs","","room","corr"),
       ("VendingStairs","售货楼梯","Vending Stairs","","room","corr")],
  "1":[("Kitchen","厨房","Kitchen","目标","obj","gold"),("Cafeteria","食堂","Cafeteria","目标","obj","gold"),
       ("Control","控制室","Control","目标","obj","gold"),("Storage","储藏室","Storage","目标","obj","gold"),
       ("Gaming","游戏室","Gaming","","room","room"),("Warehouse","仓库","Warehouse","","room","room"),
       ("Vending","售货区","Vending","","room","room"),("Pantry","储物间","Pantry","","room","room"),
       ("Lobby","大堂","Lobby","","room","room"),("Containers","集装箱","Containers","","room","room"),
       ("Delivery","送货区","Delivery","","room","room"),("Control Hallway","控制室走廊","Control Hall","","room","corr"),
       ("Cafeteria Hallway","食堂走廊","Cafeteria Hall","","room","corr"),("Gaming Hallway","游戏室走廊","Gaming Hall","","room","corr"),
       ("Lobby Hallway","大堂走廊","Lobby Hall","","room","corr"),("StorageHallway","储藏走廊","Storage Hall","","room","corr"),
       ("WarehouseEntrance","仓库入口","Warehouse Ent.","","room","corr"),("West Stairs","西楼梯","West Stairs","","room","corr"),
       ("Blue Stairs","蓝楼梯","Blue Stairs","","room","corr")],
  "2":[("Command","指挥室","Command","目标","obj","gold"),("Server","服务器室","Server","目标","obj","gold"),
       ("Meeting","会议室","Meeting","","room","room"),("Lobby","大堂","Lobby","","room","room"),
       ("Connector","连接厅","Connector","","room","room"),("Electrical","电气室","Electrical","","room","room"),
       ("IT","IT室","IT","","room","room"),("Warehouse","仓库","Warehouse","","room","room"),
       ("Observatory","观测台","Observatory","","room","room"),("Top Lobby","大堂上层","Top Lobby","","room","room"),
       ("Command Hallway","指挥走廊","Command Hall","","room","corr"),("Meeting Hallway","会议走廊","Meeting Hall","","room","corr"),
       ("West Stairs","西楼梯","West Stairs","","room","corr"),("Blue Stairs","蓝楼梯","Blue Stairs","","room","corr"),
       ("Catwalk","猫道","Catwalk","","room","corr"),("Containers","集装箱","Containers","","room","room"),
       ("Delivery","送货区","Delivery","","room","room")],
  "3":[("Helipad","直升机坪","Helipad","室外","ext","ext"),("Park","停车场","Park","室外","ext","ext")],
 },
}

MAPCFG["lair"] = {
 "mapcn":"巢穴","mapen":"Lair",
 "order":["3","2","1","0"], "default":"1",
 "names":{"3":"屋顶","2":"二楼","1":"一楼","0":"地下室"},
 "en":{"3":"ROOF","2":"2F","1":"1F","0":"B"},
 "notes":{"3":"屋顶层 · 室外","2":"面具室 + 主控室 + 服务器","1":"床铺 + 接待 + 医务室 + 军械库","0":"实验室 + 库存 + 导弹室"},
 "sites":[{"id":"1","f":"2","n":"① 面具·主控"},{"id":"2","f":"1","n":"② 床铺·接待"},
          {"id":"3","f":"1","n":"③ 医务室·军械库"},{"id":"4","f":"0","n":"④ 实验室·库存"}],
 "bombs":{"2":["1A","1B"],"1":["2A","2B","3A","3B"],"0":["4A","4B"]},
 "rooms":{
  "0":[("Lab","实验室","Lab","目标","obj","gold"),("Stock","库存室","Stock","目标","obj","gold"),
       ("Missile","导弹室","Missile","","room","room"),("Toxin","毒素室","Toxin","","room","room"),
       ("Lockers","储物间","Lockers","","room","room"),("Support","支援室","Support","","room","room"),
       ("Warehouse","仓库","Warehouse","","room","room"),("Filtration","过滤室","Filtration","","room","room"),
       ("Barrels","桶室","Barrels","","room","room"),("Electrical","电气室","Electrical","","room","room"),
       ("Docks","码头","Docks","","room","room"),("Courtyard","中庭","Courtyard","","room","room"),
       ("Missile Hallway","导弹走廊","Missile Hall","","room","corr"),("Lab Exit","实验室出口","Lab Exit","","room","corr"),
       ("Staff","职员区","Staff","","room","room"),("Shooting","射击场","Shooting","","room","room")],
  "1":[("Bunks","床铺","Bunks","目标","obj","gold"),("Reception","接待处","Reception","目标","obj","gold"),
       ("Medical","医务室","Medical","目标","obj","gold"),("Armory","军械库","Armory","目标","obj","gold"),
       ("Breifing","简报室","Briefing","","room","room"),("CCTV","监控室","CCTV","","room","room"),
       ("Booth","岗亭","Booth","","room","room"),("Maintenance","维修间","Maintenance","","room","room"),
       ("Courtyard","中庭","Courtyard","","room","room"),("Shooting","射击场","Shooting","","room","room"),
       ("Medical Hallway","医务走廊","Medical Hall","","room","corr"),("Green Hallway","绿色走廊","Green Hall","","room","corr"),
       ("Yellow Hallway","黄色走廊","Yellow Hall","","room","corr"),("Blue Hallway","蓝色走廊","Blue Hall","","room","corr"),
       ("Main Entrance","主入口","Main Ent.","","room","corr"),("Bunks Terrace","床铺露台","Bunks Terrace","室外","ext","ext"),
       ("CCTV Terrace","监控露台","CCTV Terrace","室外","ext","ext")],
  "2":[("Mask","面具室","Mask","目标","obj","gold"),("Master","主控室","Master","目标","obj","gold"),
       ("Operational","作战室","Operational","","room","room"),("Mezzanine","夹层","Mezzanine","","room","room"),
       ("Reception","接待","Reception","","room","room"),("Bathroom","洗手间","Bathroom","","room","room"),
       ("Server","服务器室","Server","","room","room"),("Six","六号房","Six","","room","room"),
       ("Storage","储藏室","Storage","","room","room"),("Bridge","天桥","Bridge","","room","room"),
       ("Gallery","走廊厅","Gallery","","room","room"),("Shooting","射击场","Shooting","","room","room"),
       ("Courtyard","中庭","Courtyard","","room","room"),("Server Hallway","服务器走廊","Server Hall","","room","corr"),
       ("Storage Hallway","储藏走廊","Storage Hall","","room","corr")],
  "3":[("Roof","屋顶","Roof","室外","ext","ext"),("Courtyard","中庭","Courtyard","室外","ext","ext")],
 },
}

MAPCFG["skyscraper"] = {
 "mapcn":"摩天","mapen":"Skyscraper",
 "order":["3","2","1"], "default":"2",
 "names":{"3":"屋顶","2":"二楼","1":"一楼"},
 "en":{"3":"ROOF","2":"2F","1":"1F"},
 "notes":{"3":"屋顶层 · 室外","2":"茶室 + 博物馆 + 卡拉OK + 办公室","1":"BBQ + 厨房 + 卧室 + 餐厅"},
 "sites":[{"id":"1","f":"2","n":"① 茶室·卡拉OK"},{"id":"2","f":"2","n":"② 博物馆·办公室"},
          {"id":"3","f":"1","n":"③ BBQ·厨房"},{"id":"4","f":"1","n":"④ 卧室·洗手间"}],
 "bombs":{"2":["1A","1B","2A","2B"],"1":["3A","3B","4A","4B"]},
 "rooms":{
  "1":[("BBQ","烧烤区","BBQ","目标","obj","gold"),("Kitchen","厨房","Kitchen","目标","obj","gold"),
       ("Bedroom","卧室","Bedroom","目标","obj","gold"),("Bathroom","洗手间","Bathroom","目标","obj","gold"),
       ("Pantry","储藏室","Pantry","","room","room"),("Delivery","送货区","Delivery","","room","room"),
       ("Lobby","大堂","Lobby","","room","room"),("Coat","衣帽间","Coat","","room","room"),
       ("Reception","前台","Reception","","room","room"),("Closet","壁橱","Closet","","room","room"),
       ("Dressing","更衣室","Dressing","","room","room"),("Restaurant","餐厅","Restaurant","","room","room"),
       ("Toilet","洗手间","Toilet","","room","room"),("Bar","吧台","Bar","","room","room"),
       ("Sushi","寿司吧","Sushi","","room","room"),("BBQ Hallway","BBQ走廊","BBQ Hall","","room","corr"),
       ("LobbyStairs","大堂楼梯","Lobby Stairs","","room","corr"),("Main Entrance","主入口","Main Ent.","","room","corr")],
  "2":[("Tea","茶室","Tea","目标","obj","gold"),("Karaoke","卡拉OK","Karaoke","目标","obj","gold"),
       ("Museum","博物馆","Museum","目标","obj","gold"),("Office","办公室","Office","目标","obj","gold"),
       ("Geisha","艺伎室","Geisha","","room","room"),("Makeup","化妆间","Makeup","","room","room"),
       ("Drums","鼓室","Drums","","room","room"),("Mezzanine","夹层","Mezzanine","","room","room"),
       ("Shrine","神龛","Shrine","","room","room"),("Dragon","龙厅","Dragon","","room","room"),
       ("VIP","VIP室","VIP","","room","room"),("Lounge","休息室","Lounge","","room","room"),
       ("Display","展示厅","Display","","room","room"),("Geisha Hallway","艺伎走廊","Geisha Hall","","room","corr"),
       ("Karaoke Hallway","卡拉OK走廊","Karaoke Hall","","room","corr"),("Geisha Connector","艺伎连廊","Geisha Conn.","","room","corr"),
       ("Terrace","露台","Terrace","室外","ext","ext")],
  "3":[("Roof","屋顶","Roof","室外","ext","ext"),("Tower","塔","Tower","室外","ext","ext")],
 },
}

MAPCFG["themepark"] = {
 "mapcn":"主题公园","mapen":"Theme Park",
 "order":["3","2","1"], "default":"2",
 "names":{"3":"屋顶","2":"二楼","1":"一楼"},
 "en":{"3":"ROOF","2":"2F","1":"1F"},
 "notes":{"3":"屋顶层 · 室外","2":"吧台 + 办公室 + 托儿所 + 床铺","1":"王座厅 + 军械库 + 实验室 + 制毒室"},
 "sites":[{"id":"1","f":"2","n":"① 吧台·办公室"},{"id":"2","f":"2","n":"② 托儿所·床铺"},
          {"id":"3","f":"1","n":"③ 王座厅·军械库"},{"id":"4","f":"1","n":"④ 实验室·制毒室"}],
 "bombs":{"2":["1A","1B","2A","2B"],"1":["3A","3B","4A","4B"]},
 "rooms":{
  "1":[("Throne","王座厅","Throne","目标","obj","gold"),("Armory","军械库","Armory","目标","obj","gold"),
       ("Lab","实验室","Lab","目标","obj","gold"),("Drug","制毒室","Drug","目标","obj","gold"),
       ("Arcade","街机厅","Arcade","","room","room"),("Barrel","桶室","Barrel","","room","room"),
       ("Dragon","龙室","Dragon","","room","room"),("Oven","烤炉房","Oven","","room","room"),
       ("Gong","锣室","Gong","","room","room"),("Tellers","柜台","Tellers","","room","room"),
       ("Toilet","洗手间","Toilet","","room","room"),("Locker","储物间","Locker","","room","room"),
       ("Blue","蓝房","Blue","","room","room"),("Maintenance","维修间","Maintenance","","room","room"),
       ("Lab Corridor","实验室走廊","Lab Corr.","","room","corr"),("Red Corridor","红色走廊","Red Corr.","","room","corr"),
       ("Locker Corridor","储物走廊","Locker Corr.","","room","corr"),("Yellow Stairs","黄楼梯","Yellow Stairs","","room","corr")],
  "2":[("Bar","吧台","Bar","目标","obj","gold"),("Office","办公室","Office","目标","obj","gold"),
       ("Day Care","托儿所","Day Care","目标","obj","gold"),("Bunk","床铺","Bunk","目标","obj","gold"),
       ("Kitchen","厨房","Kitchen","","room","room"),("Initiation","入会室","Initiation","","room","room"),
       ("Control","控制室","Control","","room","room"),("Yellow","黄房","Yellow","","room","room"),
       ("Waiting","等候室","Waiting","","room","room"),("Cash","收银室","Cash","","room","room"),
       ("Cafe","咖啡厅","Cafe","","room","room"),("Showers","淋浴间","Showers","","room","room"),
       ("Vault","金库","Vault","","room","room"),("Top Arcade","街机上层","Top Arcade","","room","room"),
       ("Cash Corridor","收银走廊","Cash Corr.","","room","corr"),("Cafe Corridor","咖啡走廊","Cafe Corr.","","room","corr")],
  "3":[("Roof","屋顶","Roof","室外","ext","ext"),("Castle","城堡","Castle","室外","ext","ext")],
 },
}

MAPCFG["emerald"] = {
 "mapcn":"翠绿平原","mapen":"Emerald Plains",
 "order":["2","1"], "default":"1",
 "names":{"2":"二楼","1":"一楼"},
 "en":{"2":"2F","1":"1F"},
 "notes":{"2":"总裁办公室 + 会议室 + 雕像厅","1":"九十号 + 泳池 + 餐厅 + 厨房"},
 "sites":[{"id":"1","f":"2","n":"① 总裁办·会议"},{"id":"2","f":"2","n":"② 雕像·画室"},
          {"id":"3","f":"1","n":"③ 九十号·泳池"},{"id":"4","f":"1","n":"④ 餐厅·厨房"}],
 "bombs":{"2":["1A","1B","2A","2B"],"1":["3A","3B","4A","4B"]},
 "rooms":{
  "1":[("Ninety","九十号","Ninety","目标","obj","gold"),("Pool","泳池","Pool","目标","obj","gold"),
       ("Dining","餐厅","Dining","目标","obj","gold"),("Kitchen","厨房","Kitchen","目标","obj","gold"),
       ("Big Mud","大泥屋","Big Mud","","room","room"),("Mud","泥屋","Mud","","room","room"),
       ("Lobby","大堂","Lobby","","room","room"),("Toilets","洗手间","Toilets","","room","room"),
       ("Cross","十字厅","Cross","","room","room"),("Wine","酒室","Wine","","room","room"),
       ("Fireplace","壁炉厅","Fireplace","","room","room"),("Pantry","储藏室","Pantry","","room","room"),
       ("Stock","库存室","Stock","","room","room"),("Lounge","休息室","Lounge","","room","room"),
       ("Bar","吧台","Bar","","room","room"),("Trash","垃圾间","Trash","","room","room"),
       ("Fountain Stairs","喷泉楼梯","Fountain Stairs","","room","corr"),("Green Stairs","绿楼梯","Green Stairs","","room","corr"),
       ("Orange Stairs","橙楼梯","Orange Stairs","","room","corr")],
  "2":[("CEO","总裁办公室","CEO","目标","obj","gold"),("Meeting","会议室","Meeting","目标","obj","gold"),
       ("Statue","雕像厅","Statue","目标","obj","gold"),("Painting","画室","Painting","目标","obj","gold"),
       ("Clock","时钟厅","Clock","","room","room"),("Folding Screen","屏风室","Folding Screen","","room","room"),
       ("Waiting","等候室","Waiting","","room","room"),("Ceramic","陶瓷室","Ceramic","","room","room"),
       ("Vault","金库","Vault","","room","room"),("Harp","竖琴室","Harp","","room","room"),
       ("Piano","钢琴室","Piano","","room","room"),("Music","音乐室","Music","","room","room"),
       ("Trophy","奖杯室","Trophy","","room","room"),("Archives","档案室","Archives","","room","room"),
       ("Library","图书室","Library","","room","room"),("Admin","行政室","Admin","","room","room"),
       ("Clock Hallway","时钟走廊","Clock Hall","","room","corr")],
 },
}

MAPCFG["kanal"] = {
 "mapcn":"运河","mapen":"Kanal",
 "order":["3","2","1","0"], "default":"1",
 "names":{"3":"屋顶","2":"二楼","1":"一楼","0":"地下室"},
 "en":{"3":"ROOF","2":"2F","1":"1F","0":"B"},
 "notes":{"3":"屋顶层 · 室外","2":"服务器 + 雷达室","1":"厨房 + 保安 + 无线电 + 接待","0":"皮划艇 + 补给 + 潜水室"},
 "sites":[{"id":"1","f":"2","n":"① 服务器·雷达"},{"id":"2","f":"1","n":"② 厨房·保安"},
          {"id":"3","f":"1","n":"③ 无线电·接待"},{"id":"4","f":"0","n":"④ 皮划艇·补给"}],
 "bombs":{"2":["1A","1B"],"1":["2A","2B","3A","3B"],"0":["4A","4B"]},
 "rooms":{
  "0":[("Kayaks","皮划艇室","Kayaks","目标","obj","gold"),("Supply","补给室","Supply","目标","obj","gold"),
       ("Garage","车库","Garage","","room","room"),("Alcove","壁龛","Alcove","","room","room"),
       ("Pipes","管道室","Pipes","","room","room"),("Bathroom","洗手间","Bathroom","","room","room"),
       ("Shower","淋浴间","Shower","","room","room"),("Locker","储物间","Locker","","room","room"),
       ("Diving","潜水室","Diving","","room","room"),("Basement Corridor","地下走廊","B.Corridor","","room","corr"),
       ("Diving Corridor","潜水走廊","Diving Corr.","","room","corr"),("Red Stairs","红楼梯","Red Stairs","","room","corr"),
       ("White Stairs","白楼梯","White Stairs","","room","corr")],
  "1":[("Kitchen","厨房","Kitchen","目标","obj","gold"),("Security","保安室","Security","目标","obj","gold"),
       ("Radio","无线电室","Radio","目标","obj","gold"),("Reception","接待处","Reception","目标","obj","gold"),
       ("Archives","档案室","Archives","","room","room"),("Model","模型室","Model","","room","room"),
       ("Museum","博物馆","Museum","","room","room"),("Meeting","会议室","Meeting","","room","room"),
       ("Lounge","休息室","Lounge","","room","room"),("Map","地图室","Map","","room","room"),
       ("Projector","放映室","Projector","","room","room"),("Gym","健身房","Gym","","room","room"),
       ("Bridge","桥","Bridge","","room","room"),("Radio Hallway","无线电走廊","Radio Hall","","room","corr"),
       ("Map Corridor","地图走廊","Map Corr.","","room","corr"),("Meeting Hallway","会议走廊","Meeting Hall","","room","corr"),
       ("White Stairs","白楼梯","White Stairs","","room","corr"),("Red Stairs","红楼梯","Red Stairs","","room","corr")],
  "2":[("Server","服务器室","Server","目标","obj","gold"),("Radar","雷达室","Radar","目标","obj","gold"),
       ("Renovations","装修区","Renovations","","room","room"),("Printer","打印室","Printer","","room","room"),
       ("Control","控制室","Control","","room","room"),("Upper Bridge","上层桥","Upper Bridge","","room","room"),
       ("Roof Entrance","屋顶入口","Roof Ent.","","room","corr"),("Radar Corridor","雷达走廊","Radar Corr.","","room","corr"),
       ("Server Corridor","服务器走廊","Server Corr.","","room","corr"),("White Stairs","白楼梯","White Stairs","","room","corr"),
       ("Red Stairs","红楼梯","Red Stairs","","room","corr")],
  "3":[("Roof","屋顶","Roof","室外","ext","ext"),("West Roof","西屋顶","West Roof","室外","ext","ext")],
 },
}

MAPCFG["outback"] = {
 "mapcn":"内陆","mapen":"Outback",
 "order":["3","2","1"], "default":"2",
 "names":{"3":"屋顶","2":"二楼","1":"一楼"},
 "en":{"3":"ROOF","2":"2F","1":"1F"},
 "notes":{"3":"屋顶层 · 室外","2":"洗衣房 + 派对室 + 办公室 + 钢琴室","1":"爬行动物馆 + 厨房 + 餐厅 + 绿房"},
 "sites":[{"id":"1","f":"2","n":"① 洗衣房·钢琴室"},{"id":"2","f":"2","n":"② 派对室·办公室"},
          {"id":"3","f":"1","n":"③ 爬行动物馆·绿房"},{"id":"4","f":"1","n":"④ 厨房·餐厅"}],
 "bombs":{"2":["1A","1B","2A","2B"],"1":["3A","3B","4A","4B"]},
 "rooms":{
  "1":[("Reptile","爬行动物馆","Reptile","目标","obj","gold"),("Green","绿房","Green","目标","obj","gold"),
       ("Kitchen","厨房","Kitchen","目标","obj","gold"),("Restaurant","餐厅","Restaurant","目标","obj","gold"),
       ("Garage","车库","Garage","","room","room"),("Bike","摩托房","Bike","","room","room"),
       ("Waiting","等候区","Waiting","","room","room"),("Shop","商店","Shop","","room","room"),
       ("Reception","前台","Reception","","room","room"),("Yellow","黄房","Yellow","","room","room"),
       ("Red","红房","Red","","room","room"),("Closet","壁橱","Closet","","room","room"),
       ("Lobby","大堂","Lobby","","room","room"),("Bathroom","洗手间","Bathroom","","room","room"),
       ("Loading","装卸区","Loading","","room","room"),("Kitchen Hallway","厨房走廊","Kitchen Hall","","room","corr"),
       ("Garage Stairs","车库楼梯","Garage Stairs","","room","corr"),("Yellow Stairs","黄楼梯","Yellow Stairs","","room","corr")],
  "2":[("Laundry","洗衣房","Laundry","目标","obj","gold"),("Piano","钢琴室","Piano","目标","obj","gold"),
       ("Party","派对室","Party","目标","obj","gold"),("Office","办公室","Office","目标","obj","gold"),
       ("Lounge","休息室","Lounge","","room","room"),("Garage","车库","Garage","","room","room"),
       ("Bull","公牛室","Bull","","room","room"),("Supplies","补给室","Supplies","","room","room"),
       ("Gaming","游戏室","Gaming","","room","room"),("Connector","连接厅","Connector","","room","room"),
       ("Dorms","宿舍","Dorms","","room","room"),("Showers","淋浴间","Showers","","room","room"),
       ("Shark","鲨鱼室","Shark","","room","room"),("Party Hallway","派对走廊","Party Hall","","room","corr"),
       ("Motel Hallway","汽车旅馆走廊","Motel Hall","","room","corr"),("Garage Stairs","车库楼梯","Garage Stairs","","room","corr"),
       ("Terrace","露台","Terrace","室外","ext","ext")],
  "3":[("Roof","屋顶","Roof","室外","ext","ext"),("Terrace","露台","Terrace","室外","ext","ext")],
 },
}

MAPCFG["fortress"] = {
 "mapcn":"堡垒","mapen":"Fortress",
 "order":["2","1"], "default":"2",
 "names":{"2":"二楼","1":"一楼"},
 "en":{"2":"2F","1":"1F"},
 "notes":{"2":"指挥官室 + 游戏室 + 宿舍 + 卧室","1":"食堂 + 枪械室 + 厨房 + 更衣室"},
 "sites":[{"id":"1","f":"2","n":"① 指挥官室·洗手间"},{"id":"2","f":"2","n":"② 游戏室·宿舍"},
          {"id":"3","f":"1","n":"③ 食堂·喷泉厅"},{"id":"4","f":"1","n":"④ 枪械室·更衣室"}],
 "bombs":{"2":["1A","1B","2A","2B"],"1":["3A","3B","4A","4B"]},
 "rooms":{
  "1":[("Cafeteria","食堂","Cafeteria","目标","obj","gold"),("Fountain","喷泉厅","Fountain","目标","obj","gold"),
       ("Gun Room","枪械室","Gun Room","目标","obj","gold"),("Changing","更衣室","Changing","目标","obj","gold"),
       ("Laundry","洗衣房","Laundry","","room","room"),("Hammam","浴室","Hammam","","room","room"),
       ("Showers","淋浴间","Showers","","room","room"),("Kitchen","厨房","Kitchen","","room","room"),
       ("Waiting","等候区","Waiting","","room","room"),("Infirmary","医务室","Infirmary","","room","room"),
       ("Sitting","起居室","Sitting","","room","room"),("Music","音乐室","Music","","room","room"),
       ("Dining","餐厅","Dining","","room","room"),("Lobby","大堂","Lobby","","room","room"),
       ("Office","办公室","Office","","room","room"),("Cafeteria Hallway","食堂走廊","Cafeteria Hall","","room","corr"),
       ("Kitchen Hallway","厨房走廊","Kitchen Hall","","room","corr"),("Main Hallway","主走廊","Main Hall","","room","corr"),
       ("Main Stairs","主楼梯","Main Stairs","","room","corr")],
  "2":[("Commander","指挥官室","Commander","目标","obj","gold"),("Bathroom","洗手间","Bathroom","目标","obj","gold"),
       ("Gaming","游戏室","Gaming","目标","obj","gold"),("Dormitory","宿舍","Dormitory","目标","obj","gold"),
       ("Shisha","水烟室","Shisha","","room","room"),("Portrait","肖像室","Portrait","","room","room"),
       ("Horse","马厩","Horse","","room","room"),("Bedroom","卧室","Bedroom","","room","room"),
       ("Fountain","喷泉厅","Fountain","","room","room"),("Mezzanine","夹层","Mezzanine","","room","room"),
       ("Renovation","装修区","Renovation","","room","room"),("Dormitory Hallway","宿舍走廊","Dorm Hall","","room","corr"),
       ("Gaming Hallway","游戏室走廊","Gaming Hall","","room","corr"),("Briefing Hallway","简报走廊","Briefing Hall","","room","corr"),
       ("Bedroom Hallway","卧室走廊","Bedroom Hall","","room","corr"),("Main Stairs","主楼梯","Main Stairs","","room","corr")],
 },
}

MAPCFG["favela"] = {
 "mapcn":"贫民窟","mapen":"Favela",
 "order":["2","1"], "default":"1",
 "names":{"2":"二楼","1":"一楼"},
 "en":{"2":"2F","1":"1F"},
 "notes":{"2":"服务器 + 黑客室 + 床铺 + 办公室","1":"粉屋 + 黄屋 + 绿屋 + 蓝屋"},
 "sites":[{"id":"1","f":"2","n":"① 服务器·黑客室"},{"id":"2","f":"2","n":"② 床铺·办公室"},
          {"id":"3","f":"1","n":"③ 粉屋"},{"id":"4","f":"1","n":"④ 黄屋·绿屋"}],
 "bombs":{"2":["1A","1B","2A","2B"],"1":["3A","3B","4A","4B"]},
 "rooms":{
  "1":[("Pink","粉屋","Pink","目标","obj","gold"),("Yellow","黄屋","Yellow","目标","obj","gold"),
       ("Green","绿屋","Green","目标","obj","gold"),("Pink Kitchen","粉屋厨房","Pink Kitchen","","room","room"),
       ("Laundry","洗衣房","Laundry","","room","room"),("Solarium","阳光房","Solarium","","room","room"),
       ("Gaming","游戏室","Gaming","","room","room"),("Blue","蓝屋","Blue","","room","room"),
       ("GreenBathroom","绿屋洗手间","Green Bath","","room","room"),("Blue Kitchen","蓝屋厨房","Blue Kitchen","","room","room"),
       ("Blue Bedroom","蓝屋卧室","Blue Bedroom","","room","room"),("Yellow Stairs","黄楼梯","Yellow Stairs","","room","corr")],
  "2":[("Servers","服务器室","Servers","目标","obj","gold"),("Haker","黑客室","Haker","目标","obj","gold"),
       ("Bunks","床铺","Bunks","目标","obj","gold"),("Office","办公室","Office","目标","obj","gold"),
       ("Mezzanine","夹层","Mezzanine","","room","room"),("Red","红屋","Red","","room","room"),
       ("Storage","储藏室","Storage","","room","room"),("Armory","军械库","Armory","","room","room"),
       ("Red Stairs","红楼梯","Red Stairs","","room","corr"),("Yellow Stairs","黄楼梯","Yellow Stairs","","room","corr")],
 },
}

MAPCFG["stadiumbravo"] = {
 "mapcn":"体育场","mapen":"Stadium Bravo",
 "order":["2","1"], "default":"2",
 "names":{"2":"二楼","1":"一楼"},
 "en":{"2":"2F","1":"1F"},
 "notes":{"2":"军械库 + 档案室 + 顶层套房 + VIP","1":"服务器 + 淋浴间 + 厨房 + 日出房"},
 "sites":[{"id":"1","f":"2","n":"① 军械库·档案"},{"id":"2","f":"2","n":"② 顶层套房·VIP"},
          {"id":"3","f":"1","n":"③ 服务器·淋浴"},{"id":"4","f":"1","n":"④ 厨房"}],
 "bombs":{"2":["1A","1B","2A","2B"],"1":["3A","3B","4A","4B"]},
 "rooms":{
  "1":[("Servers","服务器室","Servers","目标","obj","gold"),("Showers","淋浴间","Showers","目标","obj","gold"),
       ("Kitchen","厨房","Kitchen","目标","obj","gold"),("Lobby","大堂","Lobby","","room","room"),
       ("Toilets","洗手间","Toilets","","room","room"),("Delivery","送货区","Delivery","","room","room"),
       ("Supply","补给室","Supply","","room","room"),("Sunrise","日出房","Sunrise","","room","room"),
       ("Tellers","柜台","Tellers","","room","room"),("Ventilation","通风室","Ventilation","","room","room"),
       ("Shower Hallway","淋浴走廊","Shower Hall","","room","corr"),("Kitchen Hallway","厨房走廊","Kitchen Hall","","room","corr"),
       ("Sunrise Hallway","日出走廊","Sunrise Hall","","room","corr"),("VentilationHallway","通风走廊","Vent Hall","","room","corr"),
       ("Sunrise Entrance","日出入口","Sunrise Ent.","","room","corr"),("Main Stairs","主楼梯","Main Stairs","","room","corr")],
  "2":[("Armory","军械库","Armory","目标","obj","gold"),("Archives","档案室","Archives","目标","obj","gold"),
       ("Penthouse","顶层套房","Penthouse","目标","obj","gold"),("VIP","VIP室","VIP","目标","obj","gold"),
       ("Armory Desk","军械库台","Armory Desk","","room","room"),("Fountain","喷泉厅","Fountain","","room","room"),
       ("Offices","办公室","Offices","","room","room"),("Hookah","水烟房","Hookah","","room","room"),
       ("Bathroom","洗手间","Bathroom","","room","room"),("Guitar","吉他室","Guitar","","room","room"),
       ("Hookah Connector","水烟连廊","Hookah Conn.","","room","corr"),("Hookah Hallway","水烟走廊","Hookah Hall","","room","corr"),
       ("VIP Hallway","VIP走廊","VIP Hall","","room","corr"),("Main Stairs","主楼梯","Main Stairs","","room","corr")],
 },
}


# ===== 快速匹配经典老图 (house/hereford/plane/yacht/tower) =====

MAPCFG["house"] = {
 "mapcn":"小屋","mapen":"House",
 "order":["3", "2", "1", "0"], "default":"2",
 "names":{"0": "地下室", "1": "一楼", "2": "二楼", "3": "屋顶"},
 "en":{"0": "B", "1": "1F", "2": "2F", "3": "ROOF"},
 "notes":{"0": "车库·仓库包点,含健身房、洗衣房", "1": "厨房·餐厅包点,含客厅电视房与办公室", "2": "主卧衣帽间、粉色儿童房两处包点所在层", "3": "室外屋顶,环绕建筑外圈"},
 "sites":[{"id":"1","f":"2","n":"① 主卧·衣帽间"},{"id":"2","f":"2","n":"② 粉色儿童房·衣帽间"},{"id":"3","f":"1","n":"③ 厨房·餐厅"},{"id":"4","f":"0","n":"④ 车库·仓库"}],
 "bombs":{"0": ["4A", "4B"], "1": ["3A", "3B"], "2": ["1A", "1B", "2A", "2B"]},
 "rooms":{
  "3":[("APC","装甲车","APC","","room","ext"),("Front Yard","前院","Front Yard","","room","ext"),("Garage Front","车库前","Garage Front","","room","ext"),("Garage Side","车库侧","Garage Side","","room","ext"),("Patio","露台","Patio","","room","ext"),("Roof","屋顶","Roof","","room","ext"),("Side Street","侧街","Side Street","","room","ext"),("Treehouse","树屋","Treehouse","","room","ext"),("Treehouse Alley","树屋小巷","Treehouse Alley","","room","ext")],
  "2":[("APC","装甲车","APC","","room","ext"),("Back Stairs","后楼梯","Back Stairs","","room","corr"),("Bathroom","浴室","Bathroom","","room","room"),("Bathroom Hallway","浴室走廊","Bathroom Hallway","","room","corr"),("Car","汽车房","Car","","room","room"),("Front Balcony","前阳台","Front Balcony","","room","ext"),("Front Yard","前院","Front Yard","","room","ext"),("Garage Front","车库前","Garage Front","","room","ext"),("Garage Side","车库侧","Garage Side","","room","ext"),("Lobby","大厅","Lobby","","room","room"),("Lobby Stairs","大厅楼梯","Lobby Stairs","","room","corr"),("Master","主卧","Master","目标","obj","gold"),("Master Dressing","主卧衣帽间","Master Dressing","目标","obj","gold"),("Patio","露台","Patio","","room","ext"),("Pink","粉色儿童房","Pink","目标","obj","gold"),("Pink Dressing","粉色房衣帽间","Pink Dressing","目标","obj","gold"),("Play","玩具房","Play","","room","room"),("Porch","门廊","Porch","","room","ext"),("Reading","阅读室","Reading","","room","room"),("Reading Balcony","阅读室阳台","Reading Balcony","","room","ext"),("Red Stairs","红色楼梯","Red Stairs","","room","corr"),("Side Street","侧街","Side Street","","room","ext"),("Top Hallway","顶层走廊","Top Hallway","","room","corr"),("Treehouse","树屋","Treehouse","","room","ext"),("Treehouse Alley","树屋小巷","Treehouse Alley","","room","ext")],
  "1":[("APC","装甲车","APC","","room","ext"),("Back Stairs","后楼梯","Back Stairs","","room","corr"),("Connector","连接走廊","Connector","","room","corr"),("Dining","餐厅","Dining","目标","obj","gold"),("Front Balcony","前阳台","Front Balcony","","room","ext"),("Front Yard","前院","Front Yard","","room","ext"),("Gaming","游戏室","Gaming","","room","room"),("Garage Front","车库前","Garage Front","","room","ext"),("Garage Side","车库侧","Garage Side","","room","ext"),("Kitchen","厨房","Kitchen","目标","obj","gold"),("Kitchen Stairs","厨房楼梯","Kitchen Stairs","","room","corr"),("Lobby","大厅","Lobby","","room","room"),("Lobby Stairs","大厅楼梯","Lobby Stairs","","room","corr"),("Music","音乐室","Music","","room","room"),("Office","办公室","Office","","room","room"),("Patio","露台","Patio","","room","ext"),("Porch","门廊","Porch","","room","ext"),("Red Stairs","红色楼梯","Red Stairs","","room","corr"),("Side Street","侧街","Side Street","","room","ext"),("TV","电视房","TV","","room","room"),("TV Entrance","电视房入口","TV Entrance","","room","corr"),("Treehouse","树屋","Treehouse","","room","ext"),("Treehouse Alley","树屋小巷","Treehouse Alley","","room","ext")],
  "0":[("APC","装甲车","APC","","room","ext"),("Back Stairs","后楼梯","Back Stairs","","room","corr"),("Depot","仓库","Depot","目标","obj","gold"),("Depot Stairs","仓库楼梯","Depot Stairs","","room","corr"),("Front Yard","前院","Front Yard","","room","ext"),("Garage","车库","Garage","目标","obj","gold"),("Garage Entrance","车库入口","Garage Entrance","","room","corr"),("Garage Front","车库前","Garage Front","","room","ext"),("Garage Side","车库侧","Garage Side","","room","ext"),("Gym","健身房","Gym","","room","room"),("Kitchen Stairs","厨房楼梯","Kitchen Stairs","","room","corr"),("Laundry","洗衣房","Laundry","","room","room"),("Patio","露台","Patio","","room","ext"),("Side Street","侧街","Side Street","","room","ext"),("Treehouse","树屋","Treehouse","","room","ext"),("Treehouse Alley","树屋小巷","Treehouse Alley","","room","ext")],
 },
}

MAPCFG["tower"] = {
 "mapcn":"高塔","mapen":"Tower",
 "order":["5", "4", "3", "2", "1"], "default":"2",
 "names":{"1": "一楼", "2": "二楼", "3": "夹层", "4": "顶层", "5": "屋顶"},
 "en":{"1": "1F", "2": "2F", "3": "3F", "4": "4F", "5": "ROOF"},
 "notes":{"1": "旋转餐厅层,含③酒吧④厨房两个包点", "2": "办公室·画廊·展厅层,含①CEO办公室②展厅两个包点", "3": "猫道与通风管道夹层", "4": "屋顶通道与通风管层(含北/南屋顶室外区)", "5": "室外·塔顶天台"},
 "sites":[{"id":"1","f":"2","n":"① CEO办公室·会议室"},{"id":"2","f":"2","n":"② 展厅·画廊"},{"id":"3","f":"1","n":"③ 酒吧·餐厅"},{"id":"4","f":"1","n":"④ 厨房·电玩区"}],
 "bombs":{"1": ["3A", "3B", "4A", "4B"], "2": ["1A", "1B", "2A", "2B"]},
 "rooms":{
  "5":[("Roof","屋顶","Roof","","room","ext")],
  "4":[("A","A区","A","","room","room"),("B","B区","B","","room","room"),("East Vent","东通风口","East Vent","","room","corr"),("Elevator","电梯","Elevator","","room","room"),("NORTH ROOF","北屋顶","NORTH ROOF","","room","ext"),("North Rappel","北速降点","North Rappel","","room","corr"),("North Vent","北通风口","North Vent","","room","corr"),("Roof Access","屋顶入口","Roof Access","","room","ext"),("SOUTH ROOF","南屋顶","SOUTH ROOF","","room","ext"),("South Rappel","南速降点","South Rappel","","room","corr"),("West Vent","西通风口","West Vent","","room","corr")],
  "3":[("Catwalk","猫道","Catwalk","","room","corr"),("East Vent","东通风口","East Vent","","room","corr"),("Elevator","电梯","Elevator","","room","room"),("North Rappel","北速降点","North Rappel","","room","corr"),("North Vent","北通风口","North Vent","","room","corr"),("South Rappel","南速降点","South Rappel","","room","corr"),("Ventilation","通风管道室","Ventilation","","room","corr"),("West Vent","西通风口","West Vent","","room","corr")],
  "2":[("Bathroom","卫生间","Bathroom","","room","room"),("Blue","蓝厅","Blue","","room","room"),("Blue Entrance","蓝厅入口","Blue Entrance","","room","corr"),("CEO","CEO办公室","CEO","目标","obj","gold"),("CEO Hallway","CEO走廊","CEO Hallway","","room","corr"),("CEO Reception","CEO接待处","CEO Reception","","room","room"),("Center Atrium","中央中庭","Center Atrium","","room","room"),("East Atrium","东中庭","East Atrium","","room","room"),("East Balcony","东阳台","East Balcony","","room","ext"),("East Stairs","东楼梯","East Stairs","","room","corr"),("Elevator","电梯","Elevator","","room","room"),("ElevatorHallway","电梯走廊","ElevatorHallway","","room","corr"),("Exhibit","展厅","Exhibit","目标","obj","gold"),("Exhibit Hallway","展厅走廊","Exhibit Hallway","","room","corr"),("Gallery","画廊","Gallery","目标","obj","gold"),("Gift Shop","礼品店","Gift Shop","","room","room"),("Info","问询处","Info","","room","room"),("Lantern","灯笼厅","Lantern","","room","room"),("Media","媒体室","Media","","room","room"),("Meeting","会议室","Meeting","目标","obj","gold"),("North Rappel","北速降点","North Rappel","","room","corr"),("North Stairs","北楼梯","North Stairs","","room","corr"),("Offices","办公室","Offices","","room","room"),("Offices Hallway","办公室走廊","Offices Hallway","","room","corr"),("Server","服务器机房","Server","","room","room"),("South Rappel","南速降点","South Rappel","","room","corr"),("Supply","储藏室","Supply","","room","room"),("West Atrium","西中庭","West Atrium","","room","room"),("West Balcony","西阳台","West Balcony","","room","ext"),("West Stairs","西楼梯","West Stairs","","room","corr")],
  "1":[("Bar","酒吧","Bar","目标","obj","gold"),("Bar Hallway","酒吧走廊","Bar Hallway","","room","corr"),("Bird","飞鸟厅","Bird","","room","room"),("Bonsai","盆景厅","Bonsai","","room","room"),("Center Atrium","中央中庭","Center Atrium","","room","room"),("East Atrium","东中庭","East Atrium","","room","room"),("East Balcony","东阳台","East Balcony","","room","ext"),("East Observatory","东观景台","East Observatory","","room","room"),("East Stairs","东楼梯","East Stairs","","room","corr"),("Elevator","电梯","Elevator","","room","room"),("Fountain","喷泉","Fountain","","room","room"),("Gaming","电玩区","Gaming","目标","obj","gold"),("Kitchen","厨房","Kitchen","目标","obj","gold"),("Lounge","休息室","Lounge","","room","room"),("MainReception","主接待处","MainReception","","room","room"),("North Rappel","北速降点","North Rappel","","room","corr"),("North Stairs","北楼梯","North Stairs","","room","corr"),("Restaurant","餐厅","Restaurant","目标","obj","gold"),("Restaurant Hallway","餐厅走廊","Restaurant Hallway","","room","corr"),("RestaurantReception","餐厅接待处","RestaurantReception","","room","room"),("South Rappel","南速降点","South Rappel","","room","corr"),("Tea","茶室","Tea","","room","room"),("Traditional","传统厅","Traditional","","room","room"),("West Atrium","西中庭","West Atrium","","room","room"),("West Balcony","西阳台","West Balcony","","room","ext"),("West Observatory","西观景台","West Observatory","","room","room"),("West Stairs","西楼梯","West Stairs","","room","corr"),("Yellow","黄厅","Yellow","","room","room")],
 },
}

MAPCFG["hereford"] = {
 "mapcn":"赫里福德基地","mapen":"Hereford Base",
 "order":["4", "3", "2", "1", "0"], "default":"2",
 "names":{"0": "一楼", "1": "二楼", "2": "三楼", "3": "阁楼", "4": "屋顶"},
 "en":{"0": "1F", "1": "2F", "2": "3F", "3": "4F", "4": "ROOF"},
 "notes":{"0": "底层,酿造/发酵,包点④ 酿造室·发酵室", "1": "厨房/餐厅层,包点③ 厨房·餐厅", "2": "主卧/浴室层,包点② 主卧·浴室", "3": "阁楼层,军械库/拖拉机间,顶层包点① 北/南阁楼", "4": "室外(屋顶层)"},
 "sites":[{"id":"1","f":"3","n":"① 北阁楼·南阁楼"},{"id":"2","f":"2","n":"② 主卧·浴室"},{"id":"3","f":"1","n":"③ 厨房·餐厅"},{"id":"4","f":"0","n":"④ 酿造室·发酵室"}],
 "bombs":{"0": ["4A", "4B"], "1": ["3A", "3B"], "2": ["2A", "2B"], "3": ["1A", "1B"]},
 "rooms":{
  "4":[("Barnyard","谷仓院","Barnyard","","room","ext"),("East Courtyard","东庭院","East Courtyard","","room","ext"),("Garage Roof","车库顶","Garage Roof","","room","ext"),("Rooftop","屋顶","Rooftop","","room","ext"),("Shooting Range","靶场","Shooting Range","","room","ext"),("Spitfire","喷火战机","Spitfire","","room","ext"),("Street","街道","Street","","room","ext"),("Tower","塔楼","Tower","","room","ext"),("West Courtyard","西庭院","West Courtyard","","room","ext")],
  "3":[("Armory","军械库","Armory","","room","room"),("Attic Middle","阁楼中部","Attic Middle","","room","room"),("Attic North","北阁楼","Attic North","目标","obj","gold"),("Attic South","南阁楼","Attic South","目标","obj","gold"),("Barnyard","谷仓院","Barnyard","","room","ext"),("Blue Stairs","蓝色楼梯","Blue Stairs","","room","corr"),("East Courtyard","东庭院","East Courtyard","","room","ext"),("Garage Roof","车库顶","Garage Roof","","room","ext"),("Main Stairs","主楼梯","Main Stairs","","room","corr"),("Outside Stairs","室外楼梯","Outside Stairs","","room","corr"),("Shooting Range","靶场","Shooting Range","","room","ext"),("Spitfire","喷火战机","Spitfire","","room","ext"),("Street","街道","Street","","room","ext"),("Tower","塔楼","Tower","","room","ext"),("Tractor","拖拉机间","Tractor","","room","room"),("Tractor Balcony","拖拉机阳台","Tractor Balcony","","room","ext"),("West Courtyard","西庭院","West Courtyard","","room","ext")],
  "2":[("Barnyard","谷仓院","Barnyard","","room","ext"),("Bathroom","浴室","Bathroom","目标","obj","gold"),("Bathroom Balcony","浴室阳台","Bathroom Balcony","","room","ext"),("Blue Stairs","蓝色楼梯","Blue Stairs","","room","corr"),("Closet","衣帽间","Closet","","room","room"),("East Courtyard","东庭院","East Courtyard","","room","ext"),("Garage Roof","车库顶","Garage Roof","","room","ext"),("Kids","儿童房","Kids","","room","room"),("Laundry","洗衣房","Laundry","","room","room"),("Loom","织布间","Loom","","room","room"),("Loom Balcony","织布间阳台","Loom Balcony","","room","ext"),("Main Stairs","主楼梯","Main Stairs","","room","corr"),("Master","主卧","Master","目标","obj","gold"),("Master Hallway","主卧走廊","Master Hallway","","room","corr"),("Ninety","九十房","Ninety","","room","room"),("Outside Stairs","室外楼梯","Outside Stairs","","room","corr"),("Sewing","缝纫室","Sewing","","room","room"),("Shooting Range","靶场","Shooting Range","","room","ext"),("Spitfire","喷火战机","Spitfire","","room","ext"),("Street","街道","Street","","room","ext"),("Tower","塔楼","Tower","","room","ext"),("West Courtyard","西庭院","West Courtyard","","room","ext")],
  "1":[("Barn","谷仓","Barn","","room","room"),("Barnyard","谷仓院","Barnyard","","room","ext"),("Blue Stairs","蓝色楼梯","Blue Stairs","","room","corr"),("Dining","餐厅","Dining","目标","obj","gold"),("East Courtyard","东庭院","East Courtyard","","room","ext"),("Foyer","门厅","Foyer","","room","room"),("Garage","车库","Garage","","room","room"),("Garage Hallway","车库走廊","Garage Hallway","","room","corr"),("Kitchen","厨房","Kitchen","目标","obj","gold"),("Kitchen Hallway","厨房走廊","Kitchen Hallway","","room","corr"),("Living","客厅","Living","","room","room"),("Living Hallway","客厅走廊","Living Hallway","","room","corr"),("Main Stairs","主楼梯","Main Stairs","","room","corr"),("Piano","钢琴房","Piano","","room","room"),("Prep","备餐间","Prep","","room","room"),("Shooting Range","靶场","Shooting Range","","room","ext"),("Spitfire","喷火战机","Spitfire","","room","ext"),("Street","街道","Street","","room","ext"),("Tower","塔楼","Tower","","room","ext"),("West Courtyard","西庭院","West Courtyard","","room","ext")],
  "0":[("Barn","谷仓","Barn","","room","room"),("Barnyard","谷仓院","Barnyard","","room","ext"),("Barrel","酒桶间","Barrel","","room","room"),("Blue Stairs","蓝色楼梯","Blue Stairs","","room","corr"),("Brewery","酿造室","Brewery","目标","obj","gold"),("Brewery Hallway","酿造室走廊","Brewery Hallway","","room","corr"),("East Courtyard","东庭院","East Courtyard","","room","ext"),("East Tunnel","东隧道","East Tunnel","","room","corr"),("Fermentation","发酵室","Fermentation","目标","obj","gold"),("Generator","发电机房","Generator","","room","room"),("Main Stairs","主楼梯","Main Stairs","","room","corr"),("Shooting Range","靶场","Shooting Range","","room","ext"),("Spitfire","喷火战机","Spitfire","","room","ext"),("Street","街道","Street","","room","ext"),("Tower","塔楼","Tower","","room","ext"),("West Courtyard","西庭院","West Courtyard","","room","ext"),("West Tunnel","西隧道","West Tunnel","","room","corr"),("Workshop","工作间","Workshop","","room","room"),("Workshop Hallway","工作间走廊","Workshop Hallway","","room","corr")],
 },
}

MAPCFG["yacht"] = {
 "mapcn":"游艇","mapen":"Yacht",
 "order":["5", "4", "3", "2", "1"], "default":"2",
 "names":{"1": "引擎甲板", "2": "中层甲板", "3": "上层甲板", "4": "顶层甲板", "5": "屋顶"},
 "en":{"1": "ENGINE", "2": "MID", "3": "UPPER", "4": "TOP", "5": "ROOF"},
 "notes":{"1": "引擎甲板,引擎室·服务器室包点(④)", "2": "中层甲板,厨房·餐厅与控制室·宿舍两个包点(②③),防守主战场", "3": "上层甲板,赌场·主卧·扑克室", "4": "顶层甲板,驾驶舱·地图室包点(①)", "5": "室外;屋顶与停机坪露天区"},
 "sites":[{"id":"1","f":"4","n":"① 驾驶舱·地图室"},{"id":"2","f":"2","n":"② 厨房·餐厅"},{"id":"3","f":"2","n":"③ 控制室·宿舍"},{"id":"4","f":"1","n":"④ 引擎室·服务器室"}],
 "bombs":{"1": ["4A", "4B"], "2": ["2A", "2B", "3A", "3B"], "4": ["1A", "1B"]},
 "rooms":{
  "5":[("Anchor","锚区","Anchor","","room","ext"),("Boreal Entrance","北境入口","Boreal Entrance","","room","corr"),("East Breach","东破口","East Breach","","room","ext"),("East Glacier","东冰川","East Glacier","","room","ext"),("Frozen River","冰河","Frozen River","","room","ext"),("Helipad","停机坪","Helipad","","room","ext"),("Rear Deck","后甲板","Rear Deck","","room","ext"),("Roof","屋顶","Roof","","room","ext"),("Spa Deck","水疗甲板","Spa Deck","","room","ext"),("Submarine","潜水艇","Submarine","","room","ext"),("West Breach","西破口","West Breach","","room","ext"),("West Glacier","西冰川","West Glacier","","room","ext"),("Zodiac","充气艇","Zodiac","","room","ext")],
  "4":[("Anchor","锚区","Anchor","","room","ext"),("Boreal Entrance","北境入口","Boreal Entrance","","room","corr"),("Cockpit","驾驶舱","Cockpit","目标","obj","gold"),("Cockpit Balcony","驾驶舱阳台","Cockpit Balcony","","room","ext"),("Cockpit Hallway","驾驶舱走廊","Cockpit Hallway","","room","corr"),("East Balcony","东阳台","East Balcony","","room","ext"),("East Breach","东破口","East Breach","","room","ext"),("East Glacier","东冰川","East Glacier","","room","ext"),("Frozen River","冰河","Frozen River","","room","ext"),("Helipad","停机坪","Helipad","","room","ext"),("Helipad Entrance","停机坪入口","Helipad Entrance","","room","corr"),("Maps","地图室","Maps","目标","obj","gold"),("Office","办公室","Office","","room","room"),("Rear Deck","后甲板","Rear Deck","","room","ext"),("Spa Deck","水疗甲板","Spa Deck","","room","ext"),("Submarine","潜水艇","Submarine","","room","ext"),("Top Stairs","顶层楼梯","Top Stairs","","room","corr"),("West Balcony","西阳台","West Balcony","","room","ext"),("West Breach","西破口","West Breach","","room","ext"),("West Glacier","西冰川","West Glacier","","room","ext"),("Zodiac","充气艇","Zodiac","","room","ext")],
  "3":[("Anchor","锚区","Anchor","","room","ext"),("Back Stairs","后楼梯","Back Stairs","","room","corr"),("Bathroom","卫生间","Bathroom","","room","room"),("Boreal Entrance","北境入口","Boreal Entrance","","room","corr"),("Casino","赌场","Casino","","room","room"),("Casino Hallway","赌场走廊","Casino Hallway","","room","corr"),("East Breach","东破口","East Breach","","room","ext"),("East Deck","东甲板","East Deck","","room","ext"),("East Glacier","东冰川","East Glacier","","room","ext"),("Front Deck","前甲板","Front Deck","","room","ext"),("Front Stairs","前楼梯","Front Stairs","","room","corr"),("Frozen River","冰河","Frozen River","","room","ext"),("Globe Hallway","地球仪走廊","Globe Hallway","","room","corr"),("King","国王套房","King","","room","room"),("Kitchen Stairs","厨房楼梯","Kitchen Stairs","","room","corr"),("Lounge","休息室","Lounge","","room","room"),("Master","主卧","Master","","room","room"),("Master Hallway","主卧走廊","Master Hallway","","room","corr"),("Poker","扑克室","Poker","","room","room"),("Rear Deck","后甲板","Rear Deck","","room","ext"),("Spa Deck","水疗甲板","Spa Deck","","room","ext"),("Submarine","潜水艇","Submarine","","room","ext"),("Top Stairs","顶层楼梯","Top Stairs","","room","corr"),("West Breach","西破口","West Breach","","room","ext"),("West Deck","西甲板","West Deck","","room","ext"),("West Glacier","西冰川","West Glacier","","room","ext"),("Zodiac","充气艇","Zodiac","","room","ext")],
  "2":[("Anchor","锚区","Anchor","","room","ext"),("Back Stairs","后楼梯","Back Stairs","","room","corr"),("Boreal","北境厅","Boreal","","room","room"),("Boreal Entrance","北境入口","Boreal Entrance","","room","corr"),("Cafeteria","餐厅","Cafeteria","目标","obj","gold"),("Cafeteria Hallway","餐厅走廊","Cafeteria Hallway","","room","corr"),("Control","控制室","Control","目标","obj","gold"),("Dorms","宿舍","Dorms","目标","obj","gold"),("East Breach","东破口","East Breach","","room","ext"),("East Glacier","东冰川","East Glacier","","room","ext"),("Engine Stairs","引擎楼梯","Engine Stairs","","room","corr"),("Front Stairs","前楼梯","Front Stairs","","room","corr"),("Frozen River","冰河","Frozen River","","room","ext"),("Infirmary","医务室","Infirmary","","room","room"),("Kitchen","厨房","Kitchen","目标","obj","gold"),("Kitchen Hallway","厨房走廊","Kitchen Hallway","","room","corr"),("Kitchen Stairs","厨房楼梯","Kitchen Stairs","","room","corr"),("Pantry","食品储藏室","Pantry","","room","room"),("Rear Deck","后甲板","Rear Deck","","room","ext"),("Submarine","潜水艇","Submarine","","room","ext"),("Utility","设备间","Utility","","room","room"),("West Breach","西破口","West Breach","","room","ext"),("West Glacier","西冰川","West Glacier","","room","ext"),("Zodiac","充气艇","Zodiac","","room","ext")],
  "1":[("Back Entrance","后入口","Back Entrance","","room","corr"),("Back Stairs","后楼梯","Back Stairs","","room","corr"),("East Breach","东破口","East Breach","","room","ext"),("East Glacier","东冰川","East Glacier","","room","ext"),("Engine","引擎室","Engine","目标","obj","gold"),("Engine Hallway","引擎走廊","Engine Hallway","","room","corr"),("Engine Stairs","引擎楼梯","Engine Stairs","","room","corr"),("Front Stairs","前楼梯","Front Stairs","","room","corr"),("Frozen River","冰河","Frozen River","","room","ext"),("Ladder","梯子","Ladder","","room","corr"),("Rear Deck","后甲板","Rear Deck","","room","ext"),("Server","服务器室","Server","目标","obj","gold"),("Storage","储藏室","Storage","","room","room"),("Submarine","潜水艇","Submarine","","room","ext"),("West Breach","西破口","West Breach","","room","ext"),("West Glacier","西冰川","West Glacier","","room","ext"),("Zodiac","充气艇","Zodiac","","room","ext")],
 },
}

MAPCFG["plane"] = {
 "mapcn":"总统专机","mapen":"Presidential Plane",
 "order":["4", "3", "2", "1"], "default":"2",
 "names":{"1": "货舱层", "2": "主客舱", "3": "上层", "4": "屋顶"},
 "en":{"1": "CARGO", "2": "MAIN", "3": "UPPER", "4": "ROOF"},
 "notes":{"1": "货舱层:货舱包点、行李舱、储藏室与医务室,厨房经舱口下贯至此", "2": "主客舱层:会议室/办公室、新闻发布室、厨房三处包点集中,含卧室与安保室", "3": "上层甲板:服务器室 A/B 包点、无线电室、客舱与驾驶舱楼梯", "4": "室外机顶层,前后餐勤区/登机口/服务门是外部进攻立足点"},
 "sites":[{"id":"1","f":"2","n":"① 会议室·办公室"},{"id":"2","f":"2","n":"② 新闻发布室 A·B"},{"id":"3","f":"1","n":"③ 厨房·货舱"},{"id":"4","f":"3","n":"④ 服务器室 A·B"}],
 "bombs":{"1": ["3A", "3B"], "2": ["1A", "1B", "2A", "2B"]},
 "rooms":{
  "4":[("Back Caterer","后餐勤区","Back Caterer","","room","ext"),("Back Service Entrance","后服务门","Back Service Entrance","","room","corr"),("Back Stairway","后梯道","Back Stairway","","room","corr"),("Front Caterer","前餐勤区","Front Caterer","","room","ext"),("Front Service Entrance","前服务门","Front Service Entrance","","room","corr"),("Front Stairway","前梯道","Front Stairway","","room","corr"),("Left Wing","左机翼","Left Wing","","room","ext"),("Main Entrance","正门","Main Entrance","","room","corr"),("Reporter Entrance","记者登机口","Reporter Entrance","","room","corr"),("Right Wing","右机翼","Right Wing","","room","ext"),("Roof","机顶","Roof","","room","ext")],
  "3":[("Back Caterer","后餐勤区","Back Caterer","","room","ext"),("Back Service Entrance","后服务门","Back Service Entrance","","room","corr"),("Back Stairway","后梯道","Back Stairway","","room","corr"),("Cabin","客舱","Cabin","","room","room"),("Cabin Staff","乘务舱","Cabin Staff","","room","room"),("Cockpit Stairs","驾驶舱楼梯","Cockpit Stairs","","room","corr"),("Front Caterer","前餐勤区","Front Caterer","","room","ext"),("Front Service Entrance","前服务门","Front Service Entrance","","room","corr"),("Front Stairway","前梯道","Front Stairway","","room","corr"),("Left Wing","左机翼","Left Wing","","room","ext"),("Main Entrance","正门","Main Entrance","","room","corr"),("Radio","无线电室","Radio","","room","room"),("Reporter Entrance","记者登机口","Reporter Entrance","","room","corr"),("Right Wing","右机翼","Right Wing","","room","ext"),("Server A","服务器室A","Server A","目标","obj","gold"),("Server B","服务器室B","Server B","目标","obj","gold")],
  "2":[("Back Caterer","后餐勤区","Back Caterer","","room","ext"),("Back Service Entrance","后服务门","Back Service Entrance","","room","corr"),("Back Stairs","后楼梯","Back Stairs","","room","corr"),("Back Stairway","后梯道","Back Stairway","","room","corr"),("Bathroom","卫生间","Bathroom","","room","room"),("Bedroom","卧室","Bedroom","","room","room"),("Bedroom Hallway","卧室走廊","Bedroom Hallway","","room","corr"),("Changing","更衣室","Changing","","room","room"),("Cockpit Stairs","驾驶舱楼梯","Cockpit Stairs","","room","corr"),("Front Caterer","前餐勤区","Front Caterer","","room","ext"),("Front Service Entrance","前服务门","Front Service Entrance","","room","corr"),("Front Stairs","前楼梯","Front Stairs","","room","corr"),("Front Stairway","前梯道","Front Stairway","","room","corr"),("Kitchen","厨房","Kitchen","目标","obj","gold"),("Ladder","梯子","Ladder","","room","corr"),("Laundry","洗衣房","Laundry","","room","room"),("Left Wing","左机翼","Left Wing","","room","ext"),("Main Entrance","正门","Main Entrance","","room","corr"),("Meeting","会议室","Meeting","目标","obj","gold"),("Meeting Hallway","会议室走廊","Meeting Hallway","","room","corr"),("Office","办公室","Office","目标","obj","gold"),("Office Hallway","办公室走廊","Office Hallway","","room","corr"),("Pantry","备餐间","Pantry","","room","room"),("Press A","新闻发布室A","Press A","目标","obj","gold"),("Press B","新闻发布室B","Press B","目标","obj","gold"),("Reporter Entrance","记者登机口","Reporter Entrance","","room","corr"),("Right Wing","右机翼","Right Wing","","room","ext"),("Security","安保室","Security","","room","room"),("Staff","乘务室","Staff","","room","room")],
  "1":[("Back Caterer","后餐勤区","Back Caterer","","room","ext"),("Back Service Entrance","后服务门","Back Service Entrance","","room","corr"),("Back Stairs","后楼梯","Back Stairs","","room","corr"),("Back Stairway","后梯道","Back Stairway","","room","corr"),("Cargo","货舱","Cargo","目标","obj","gold"),("Front Caterer","前餐勤区","Front Caterer","","room","ext"),("Front Service Entrance","前服务门","Front Service Entrance","","room","corr"),("Front Stairs","前楼梯","Front Stairs","","room","corr"),("Front Stairway","前梯道","Front Stairway","","room","corr"),("Infirmary","医务室","Infirmary","","room","room"),("Left Wing","左机翼","Left Wing","","room","ext"),("Luggage","行李舱","Luggage","","room","room"),("Main Entrance","正门","Main Entrance","","room","corr"),("Reporter Entrance","记者登机口","Reporter Entrance","","room","corr"),("Right Wing","右机翼","Right Wing","","room","ext"),("Storage","储藏室","Storage","","room","room"),("Storage Corridor","储藏走廊","Storage Corridor","","room","corr"),("Technical","设备间","Technical","","room","room")],
 },
}
