# -*- coding: utf-8 -*-
# 各地图配置: 楼层(r6calls号)/中文名/房间中文对照/包点/包点选择器
# 房间条目: (r6calls名, 中文, 英文, kind, k, 色型)  色型 gold(目标)/corr(走廊楼梯)/room/ext(室外)
MAPCFG = {}

MAPCFG["bank"] = {
 "mapcn":"银行","mapen":"Bank",
 "order":["3","2","1","0"], "default":"1",
 "names":{"3":"屋顶","2":"二楼","1":"一楼","0":"地下室"},
 "en":{"3":"ROOF","2":"2F","1":"1F","0":"B"},
 "notes":{"3":"屋顶层 · 室外","2":"CEO办公室 + 高管室","1":"柜员 + 档案 + 开放区","0":"金库 + 储物间 + 监控"},
 "sites":[{"id":"1","f":"2","n":"① CEO·高管"},{"id":"2","f":"1","n":"② 开放区·厨房"},
          {"id":"3","f":"1","n":"③ 柜员·档案"},{"id":"4","f":"0","n":"④ 储物间·监控"}],
 "bombs":{"2":["1A","1B"],"1":["2A","2B","3A","3B"],"0":["4A","4B"]},
 "rooms":{
  "0":[("Lockers","储物间","Lockers","目标","obj","gold"),("CCTV","监控室","CCTV","目标","obj","gold"),
       ("Vault","金库","Vault","","room","room"),("Gold","黄金库","Gold","","room","room"),
       ("Cash","现金库","Cash","","room","room"),("Vault Entrance","金库入口","Vault Ent.","","room","room"),
       ("Vault Lobby","金库大厅","Vault Lobby","","room","room"),("Lockers Hallway","储物间走廊","Lockers Hall","","room","corr"),
       ("Red Hallway","红色走廊","Red Hallway","","room","corr"),("Server","服务器室","Server","","room","room"),
       ("Tunnel","隧道","Tunnel","","room","room"),("Garage","车库","Garage","","room","room"),
       ("Red Truck","红卡车","Red Truck","","room","room"),("Dock","装卸区","Dock","","room","room"),
       ("Main Stairs","主楼梯","Main Stairs","","room","corr"),("Blue Stairs","蓝楼梯","Blue Stairs","","room","corr"),
       ("Elevators","电梯","Elevators","","room","corr")],
  "1":[("Tellers","柜员区","Tellers","目标","obj","gold"),("Archives","档案室","Archives","目标","obj","gold"),
       ("Open Space","开放区","Open Space","目标","obj","gold"),("Kitchen","厨房","Kitchen","目标","obj","gold"),
       ("Tellers Office","柜员办公室","Tellers Office","","room","room"),("Lobby","大堂","Lobby","","room","room"),
       ("Admin","行政室","Admin","","room","room"),("Loan","贷款室","Loan","","room","room"),
       ("Electrical","电气室","Electrical","","room","room"),("Square","广场厅","Square","","room","room"),
       ("Printer","打印室","Printer","","room","room"),("ATMs","取款机厅","ATMs","","room","room"),
       ("Open Space Hallway","开放区走廊","O.S.Hallway","","room","corr"),("Lobby Stairs","大堂楼梯","Lobby Stairs","","room","corr"),
       ("Square Stairs","广场楼梯","Square Stairs","","room","corr"),("Main Stairs","主楼梯","Main Stairs","","room","corr"),
       ("Elevators","电梯","Elevators","","room","corr"),("Garage Roof","车库顶","Garage Roof","室外","ext","ext")],
  "2":[("CEO","CEO办公室","CEO","目标","obj","gold"),("Exec","高管室","Exec","目标","obj","gold"),
       ("Front Desk","前台","Front Desk","","room","room"),("Meeting","会议室","Meeting","","room","room"),
       ("Stock","证券室","Stock","","room","room"),("Top Square","广场上层","Top Square","","room","room"),
       ("Janitor","清洁间","Janitor","","room","room"),("Banana","香蕉拐角","Banana","","room","room"),
       ("Lobby","大堂","Lobby","","room","room"),("Loan","贷款室","Loan","","room","room"),
       ("ATMs","取款机厅","ATMs","","room","room"),("Exec Hallway","高管走廊","Exec Hall","","room","corr"),
       ("Meeting Hallway","会议室走廊","Meeting Hall","","room","corr"),("Stock Hallway","证券室走廊","Stock Hall","","room","corr"),
       ("Lobby Stairs","大堂楼梯","Lobby Stairs","","room","corr"),("Square Stairs","广场楼梯","Square Stairs","","room","corr"),
       ("Main Stairs","主楼梯","Main Stairs","","room","corr"),("Elevators","电梯","Elevators","","room","corr"),
       ("Terrace","露台","Terrace","室外","ext","ext"),("Garage Roof","车库顶","Garage Roof","室外","ext","ext")],
  "3":[("High Roof","高屋顶","High Roof","室外","ext","ext"),("Low Roof","低屋顶","Low Roof","室外","ext","ext"),
       ("Terrace","露台","Terrace","室外","ext","ext"),("Garage Roof","车库顶","Garage Roof","室外","ext","ext")],
 },
}

MAPCFG["oregon"] = {
 "mapcn":"俄勒冈","mapen":"Oregon",
 "order":["3","2","1","0"], "default":"1",
 "names":{"3":"屋顶","2":"二楼","1":"一楼","0":"地下室"},
 "en":{"3":"ROOF","2":"2F","1":"1F","0":"B"},
 "notes":{"3":"屋顶层 · 室外","2":"儿童房 + 主卧 + 阁楼","1":"厨房 + 会议室 + 餐厅","0":"冷冻库 + 地下走廊"},
 "sites":[{"id":"1","f":"2","n":"① 儿童房·主卧"},{"id":"2","f":"1","n":"② 厨房·餐厅"},
          {"id":"3","f":"1","n":"③ 会议室"},{"id":"4","f":"0","n":"④ 冷冻库·走廊"}],
 "bombs":{"2":["1A","1B"],"1":["2A","2B","3A","3B"],"0":["4A","4B"]},
 "rooms":{
  "0":[("Freezer","冷冻库","Freezer","目标","obj","gold"),("Basement Corridor","地下走廊","B.Corridor","目标","obj","gold"),
       ("Storage","储藏室","Storage","","room","room"),("Laundry","洗衣房","Laundry","","room","room"),
       ("Closet","壁橱","Closet","","room","room"),("Supply","补给室","Supply","","room","room"),
       ("Blue","蓝色房","Blue","","room","room"),("Pillar","柱厅","Pillar","","room","room"),
       ("Electric","电气室","Electric","","room","room"),("Bunker","地堡","Bunker","","room","room"),
       ("Freezer Stairs","冷冻库楼梯","Freezer Stairs","","room","corr"),("Laundry Stairs","洗衣房楼梯","Laundry Stairs","","room","corr"),
       ("Tower Stairs","塔楼楼梯","Tower Stairs","","room","corr")],
  "1":[("Kitchen","厨房","Kitchen","目标","obj","gold"),("Dining","餐厅","Dining","目标","obj","gold"),
       ("Meeting","会议室","Meeting","目标","obj","gold"),("Classroom","教室","Classroom","","room","room"),
       ("Lobby","大堂","Lobby","","room","room"),("Showers","淋浴间","Showers","","room","room"),
       ("Security","保安室","Security","","room","room"),("Split","分岔厅","Split","","room","room"),
       ("Stage","舞台","Stage","","room","room"),("Tower","塔楼","Tower","","room","room"),
       ("Garage","车库","Garage","","room","room"),("Small Tower","小塔楼","Small Tower","","room","room"),
       ("Shower Corridor","淋浴走廊","Shower Corr.","","room","corr"),("Security Corridor","保安走廊","Security Corr.","","room","corr"),
       ("Kitchen Corridor","厨房走廊","Kitchen Corr.","","room","corr"),("White Stairs","白楼梯","White Stairs","","room","corr"),
       ("Armory Stairs","军械库楼梯","Armory Stairs","","room","corr"),("TowerStairs","塔楼楼梯","Tower Stairs","","room","corr"),
       ("SmallStairs","小楼梯","Small Stairs","","room","corr")],
  "2":[("Kids","儿童房","Kids","目标","obj","gold"),("Master","主卧","Master","目标","obj","gold"),
       ("Attic","阁楼","Attic","","room","room"),("Low Attic","下阁楼","Low Attic","","room","room"),
       ("Middle","中厅","Middle","","room","room"),("Trophy","奖杯室","Trophy","","room","room"),
       ("Office","办公室","Office","","room","room"),("Armory","军械库","Armory","","room","room"),
       ("Gaming","游戏室","Gaming","","room","room"),("Dorm","宿舍","Dorm","","room","room"),
       ("Walk In","步入衣柜","Walk In","","room","room"),("Small Tower","小塔楼","Small Tower","","room","room"),
       ("Armory Corridor","军械库走廊","Armory Corr.","","room","corr"),("White Stairs","白楼梯","White Stairs","","room","corr"),
       ("Armory Stairs","军械库楼梯","Armory Stairs","","room","corr"),("TowerStairs","塔楼楼梯","Tower Stairs","","room","corr"),
       ("Balcony","阳台","Balcony","室外","ext","ext")],
  "3":[("Tower Roof","塔楼顶","Tower Roof","室外","ext","ext"),("Attic Roof","阁楼顶","Attic Roof","室外","ext","ext"),
       ("Meeting Roof","会议室顶","Meeting Roof","室外","ext","ext"),("Armory Roof","军械库顶","Armory Roof","室外","ext","ext"),
       ("Master Roof","主卧顶","Master Roof","室外","ext","ext"),("Kids Roof","儿童房顶","Kids Roof","室外","ext","ext"),
       ("Dorms Roof","宿舍顶","Dorms Roof","室外","ext","ext"),("Dining Roof","餐厅顶","Dining Roof","室外","ext","ext"),
       ("Small Tower Roof","小塔楼顶","Small Tower Roof","室外","ext","ext"),("Cat Walk","猫道","Cat Walk","室外","ext","ext")],
 },
}

MAPCFG["border"] = {
 "mapcn":"边境","mapen":"Border",
 "order":["3","2","1"], "default":"1",
 "names":{"3":"屋顶","2":"二楼","1":"一楼"},
 "en":{"3":"ROOF","2":"2F","1":"1F"},
 "notes":{"3":"屋顶层 · 室外","2":"军械库 + 档案室 + 办公室","1":"海关 + 补给 + 工作间 + 柜台"},
 "sites":[{"id":"1","f":"1","n":"① 补给·海关"},{"id":"2","f":"1","n":"② 工作间·通风"},
          {"id":"3","f":"1","n":"③ 洗手间·柜台"},{"id":"4","f":"2","n":"④ 军械库·档案"}],
 "bombs":{"1":["1A","1B","2A","2B","3A","3B"],"2":["4A","4B"]},
 "rooms":{
  "1":[("Supply","补给室","Supply","目标","obj","gold"),("Customs","海关","Customs","目标","obj","gold"),
       ("Workshop","工作间","Workshop","目标","obj","gold"),("Ventilation","通风室","Ventilation","目标","obj","gold"),
       ("Bathroom","洗手间","Bathroom","目标","obj","gold"),("Tellers","柜台","Tellers","目标","obj","gold"),
       ("Detention","拘留室","Detention","","room","room"),("Customs Desk","海关台","Customs Desk","","room","room"),
       ("Waiting","等候区","Waiting","","room","room"),("Server","服务器室","Server","","room","room"),
       ("Passport","护照处","Passport","","room","room"),("Lobby","大堂","Lobby","","room","room"),
       ("Supply Corridor","补给走廊","Supply Corr.","","room","corr"),("Ventilation Hallway","通风走廊","Vent. Hall","","room","corr"),
       ("Bathroom Hallway","洗手间走廊","Bath Hall","","room","corr"),("Main Stairs","主楼梯","Main Stairs","","room","corr"),
       ("East Stairs","东楼梯","East Stairs","","room","corr")],
  "2":[("Armory","军械库","Armory","目标","obj","gold"),("Archives","档案室","Archives","目标","obj","gold"),
       ("Armory Desk","军械库台","Armory Desk","","room","room"),("CCTV","监控室","CCTV","","room","room"),
       ("Cafeteria","食堂","Cafeteria","","room","room"),("Fountain","喷泉厅","Fountain","","room","room"),
       ("Offices","办公室","Offices","","room","room"),("Waiting","等候区","Waiting","","room","room"),
       ("Sandwich","三明治角","Sandwich","","room","room"),("Offices Hallway","办公室走廊","Offices Hall","","room","corr"),
       ("Main Stairs","主楼梯","Main Stairs","","room","corr"),("East Stairs","东楼梯","East Stairs","","room","corr")],
  "3":[("Roof","屋顶","Roof","室外","ext","ext"),("Balcony Stairs","阳台楼梯","Balcony Stairs","室外","ext","ext")],
 },
}

MAPCFG["coastline"] = {
 "mapcn":"海岸线","mapen":"Coastline",
 "order":["3","2","1"], "default":"2",
 "names":{"3":"屋顶","2":"二楼","1":"一楼"},
 "en":{"3":"ROOF","2":"2F","1":"1F"},
 "notes":{"3":"屋顶层 · 室外","2":"水烟房 + 顶层套房 + VIP","1":"蓝吧 + 日出房 + 厨房"},
 "sites":[{"id":"1","f":"2","n":"① 水烟·台球"},{"id":"2","f":"2","n":"② 套房·电视"},
          {"id":"3","f":"1","n":"③ 厨房·补给"},{"id":"4","f":"1","n":"④ 蓝吧·日出"}],
 "bombs":{"2":["1A","1B","2A","2B"],"1":["3A","3B","4A","4B"]},
 "rooms":{
  "1":[("Kitchen","厨房","Kitchen","目标","obj","gold"),("Supply","补给室","Supply","目标","obj","gold"),
       ("Blue Bar","蓝吧","Blue Bar","目标","obj","gold"),("Sunrise","日出房","Sunrise","目标","obj","gold"),
       ("Delivery","送货区","Delivery","","room","room"),("Toilets","洗手间","Toilets","","room","room"),
       ("Lobby","大堂","Lobby","","room","room"),("Security","保安室","Security","","room","room"),
       ("Sun","阳光房","Sun","","room","room"),("Library","图书室","Library","","room","room"),
       ("Cantina","餐吧","Cantina","","room","room"),("Reception","前台","Reception","","room","room"),
       ("Kitchen Hallway","厨房走廊","Kitchen Hall","","room","corr"),("Sunrise Entrance","日出入口","Sunrise Ent.","","room","corr"),
       ("Sunrise Hallway","日出走廊","Sunrise Hall","","room","corr"),("White Stairs","白楼梯","White Stairs","","room","corr"),
       ("Blue Stairs","蓝楼梯","Blue Stairs","","room","corr"),("Courtyard","中庭","Courtyard","室外","ext","ext"),
       ("Promenade","步道","Promenade","室外","ext","ext"),("Terrace","露台","Terrace","室外","ext","ext")],
  "2":[("Hookah","水烟房","Hookah","目标","obj","gold"),("Pool Table","台球室","Pool Table","目标","obj","gold"),
       ("Penthouse","顶层套房","Penthouse","目标","obj","gold"),("TV","电视室","TV","目标","obj","gold"),
       ("VIP","VIP室","VIP","","room","room"),("Pool Bar","泳池吧","Pool Bar","","room","room"),
       ("Luggage","行李房","Luggage","","room","room"),("Aqua","水族房","Aqua","","room","room"),
       ("Guitars","吉他室","Guitars","","room","room"),("Bathroom","洗手间","Bathroom","","room","room"),
       ("VIP Hallway","VIP走廊","VIP Hall","","room","corr"),("TV Hallway","电视走廊","TV Hall","","room","corr"),
       ("Hookah Hallway","水烟走廊","Hookah Hall","","room","corr"),("White Stairs","白楼梯","White Stairs","","room","corr"),
       ("Blue Stairs","蓝楼梯","Blue Stairs","","room","corr"),("Roof Drop","屋顶下沉口","Roof Drop","","room","room"),
       ("Courtyard","中庭","Courtyard","室外","ext","ext"),("Promenade","步道","Promenade","室外","ext","ext")],
  "3":[("Roof","屋顶","Roof","室外","ext","ext"),("Roof Drop","屋顶下沉口","Roof Drop","室外","ext","ext")],
 },
}

MAPCFG["consulate"] = {
 "mapcn":"领事馆","mapen":"Consulate",
 "order":["3","2","1","0"], "default":"1",
 "names":{"3":"屋顶","2":"二楼","1":"一楼","0":"地下室"},
 "en":{"3":"ROOF","2":"2F","1":"1F","0":"B"},
 "notes":{"3":"屋顶层 · 室外","2":"领事办公室 + 会议室","1":"钢琴室 + 展览 + 柜台","0":"车库 + 服务器 + 厨房"},
 "sites":[{"id":"1","f":"2","n":"① 领事办·会议"},{"id":"2","f":"1","n":"② 钢琴·展览"},
          {"id":"3","f":"1","n":"③ 休息室·服务器"},{"id":"4","f":"0","n":"④ 车库·厨房"}],
 "bombs":{"2":["1A","1B"],"1":["2A","2B","3A"],"0":["4A","4B","3B"]},
 "rooms":{
  "0":[("Garage","车库","Garage","目标","obj","gold"),("Kitchen","厨房","Kitchen","目标","obj","gold"),
       ("Servers","服务器室","Servers","目标","obj","gold"),("Coffee","咖啡角","Coffee","","room","room"),
       ("CCTV","监控室","CCTV","","room","room"),("Banana","香蕉拐角","Banana","","room","room"),
       ("Lockers","储物间","Lockers","","room","room"),("Electrical","电气室","Electrical","","room","room"),
       ("Storage","储藏室","Storage","","room","room"),("Pillar","柱厅","Pillar","","room","room"),
       ("Construction","施工区","Construction","","room","room"),("Delivery","送货区","Delivery","","room","room"),
       ("ServerHallway","服务器走廊","Server Hall","","room","corr")],
  "1":[("Piano","钢琴室","Piano","目标","obj","gold"),("Expo","展览厅","Expo","目标","obj","gold"),
       ("Lounge","休息室","Lounge","目标","obj","gold"),("Statue","雕像厅","Statue","","room","room"),
       ("Tellers","柜台","Tellers","","room","room"),("Visa","签证处","Visa","","room","room"),
       ("Emergency","应急室","Emergency","","room","room"),("Closet","壁橱","Closet","","room","room"),
       ("Lobby","大堂","Lobby","","room","room"),("Gumball","口香糖机","Gumball","","room","room"),
       ("Tellers Hallway","柜台走廊","Tellers Hall","","room","corr"),("Visa Hallway","签证走廊","Visa Hall","","room","corr"),
       ("Visa Entrance","签证入口","Visa Ent.","","room","corr"),("Piano Hallway","钢琴走廊","Piano Hall","","room","corr"),
       ("Yellow Stairs","黄楼梯","Yellow Stairs","","room","corr")],
  "2":[("CEO","领事办公室","Consul Office","目标","obj","gold"),("Meeting","会议室","Meeting","目标","obj","gold"),
       ("CEO Side","领事侧室","CEO Side","","room","room"),("Break","休息室","Break","","room","room"),
       ("Catering","餐饮室","Catering","","room","room"),("Copy","复印室","Copy","","room","room"),
       ("Soda","汽水角","Soda","","room","room"),("Admin","行政室","Admin","","room","room"),
       ("Front Office","前厅","Front Office","","room","room"),("Secretary","秘书室","Secretary","","room","room"),
       ("Bathroom","洗手间","Bathroom","","room","room"),("Long Desk","长桌厅","Long Desk","","room","room"),
       ("Meeting Hallway","会议走廊","Meeting Hall","","room","corr"),("Break Hallway","休息走廊","Break Hall","","room","corr"),
       ("Consule Hallway","领事走廊","Consul Hall","","room","corr"),("ManagerHallway","经理走廊","Manager Hall","","room","corr"),
       ("Balcony","阳台","Balcony","室外","ext","ext")],
  "3":[("Garage Roof","车库顶","Garage Roof","室外","ext","ext"),("Emergency Roof","应急顶","Emergency Roof","室外","ext","ext")],
 },
}

MAPCFG["villa"] = {
 "mapcn":"别墅","mapen":"Villa",
 "order":["3","2","1","0"], "default":"2",
 "names":{"3":"屋顶","2":"二楼","1":"一楼","0":"地下室"},
 "en":{"3":"ROOF","2":"2F","1":"1F","0":"B"},
 "notes":{"3":"屋顶层 · 室外","2":"飞行家 + 奖杯室 + 雕像厅","1":"画廊 + 图书室 + 厨房 + 餐厅","0":"酒窖 + 地穴 + 车库"},
 "sites":[{"id":"1","f":"2","n":"① 飞行家·书房"},{"id":"2","f":"2","n":"② 奖杯·雕像"},
          {"id":"3","f":"1","n":"③ 画廊·图书室"},{"id":"4","f":"1","n":"④ 厨房·餐厅"}],
 "bombs":{"2":["1A","1B","2A","2B"],"1":["3A","3B","4A","4B"]},
 "rooms":{
  "0":[("Wine","酒窖","Wine","","room","room"),("Tasting","品酒室","Tasting","","room","room"),
       ("Art","艺术室","Art","","room","room"),("Arch","拱厅","Arch","","room","room"),
       ("Office","办公室","Office","","room","room"),("Garage","车库","Garage","","room","room"),
       ("Crypt","地穴","Crypt","","room","room"),("Crypt Tunnel","地穴隧道","Crypt Tunnel","","room","corr"),
       ("Cellar Tunnel","酒窖隧道","Cellar Tunnel","","room","corr"),("Red Stairs","红楼梯","Red Stairs","","room","corr"),
       ("Back Stairs","后楼梯","Back Stairs","","room","corr"),("Pantry Stairs","储藏室楼梯","Pantry Stairs","","room","corr")],
  "1":[("Gallery","画廊","Gallery","目标","obj","gold"),("Library","图书室","Library","目标","obj","gold"),
       ("Kitchen","厨房","Kitchen","目标","obj","gold"),("Dining","餐厅","Dining","目标","obj","gold"),
       ("Living","客厅","Living","","room","room"),("Piano","钢琴室","Piano","","room","room"),
       ("China","瓷器室","China","","room","room"),("Pantry","储藏室","Pantry","","room","room"),
       ("Memorial","纪念室","Memorial","","room","room"),("Mudroom","玄关","Mudroom","","room","room"),
       ("Laundry","洗衣房","Laundry","","room","room"),("Toilet","洗手间","Toilet","","room","room"),
       ("Studio","工作室","Studio","","room","room"),("Bicycle","自行车房","Bicycle","","room","room"),
       ("Greenhouse","温室","Greenhouse","","room","room"),("Main","主厅","Main","","room","room"),
       ("Front Entrance","前门","Front Ent.","","room","corr"),("Back Hallway","后走廊","Back Hall","","room","corr"),
       ("Living Hallway","客厅走廊","Living Hall","","room","corr"),("Piano Hallway","钢琴走廊","Piano Hall","","room","corr"),
       ("Astro Stairs","星空楼梯","Astro Stairs","","room","corr"),("Red Stairs","红楼梯","Red Stairs","","room","corr"),
       ("Brown Stairs","棕楼梯","Brown Stairs","","room","corr"),("Terrace","露台","Terrace","室外","ext","ext")],
  "2":[("Aviator","飞行家","Aviator","目标","obj","gold"),("Study","书房","Study","目标","obj","gold"),
       ("Trophy","奖杯室","Trophy","目标","obj","gold"),("Statue","雕像厅","Statue","目标","obj","gold"),
       ("Master","主卧","Master","","room","room"),("Astro","星空房","Astro","","room","room"),
       ("Bathroom","洗手间","Bathroom","","room","room"),("Closet","壁橱","Closet","","room","room"),
       ("Gaming","游戏室","Gaming","","room","room"),("Bar","吧台","Bar","","room","room"),
       ("Vault","金库","Vault","","room","room"),("Skull","骷髅室","Skull","","room","room"),
       ("Ninety","九十号","Ninety","","room","room"),("Ninety Corner","九十号角","Ninety Corner","","room","room"),
       ("TrophyEntrance","奖杯入口","Trophy Ent.","","room","corr"),("Landing","楼梯平台","Landing","","room","corr"),
       ("Astro Stairs","星空楼梯","Astro Stairs","","room","corr"),("Red Stairs","红楼梯","Red Stairs","","room","corr"),
       ("Brown Stairs","棕楼梯","Brown Stairs","","room","corr")],
  "3":[("Roof","屋顶","Roof","室外","ext","ext"),("Terrace","露台","Terrace","室外","ext","ext")],
 },
}

MAPCFG["chalet"] = {
 "mapcn":"木屋","mapen":"Chalet",
 "order":["3","2","1","0"], "default":"1",
 "names":{"3":"屋顶","2":"二楼","1":"一楼","0":"地下室"},
 "en":{"3":"ROOF","2":"2F","1":"1F","0":"B"},
 "notes":{"3":"屋顶层 · 室外","2":"主卧 + 办公室 + 图书室","1":"游戏室 + 吧台 + 餐厅 + 厨房","0":"酒窖 + 蓝房 + 车库"},
 "sites":[{"id":"1","f":"2","n":"① 主卧·办公室"},{"id":"2","f":"1","n":"② 游戏室·吧台"},
          {"id":"3","f":"1","n":"③ 餐厅·厨房"},{"id":"4","f":"0","n":"④ 酒窖·蓝房"}],
 "bombs":{"2":["1A","1B"],"1":["2A","2B","3A","3B"],"0":["4A","4B"]},
 "rooms":{
  "0":[("Wine","酒窖","Wine","目标","obj","gold"),("Blue","蓝房","Blue","目标","obj","gold"),
       ("Garage","车库","Garage","","room","room"),("Car Garage","大车库","Car Garage","","room","room"),
       ("Storage","储藏室","Storage","","room","room"),("Basement Hallway","地下走廊","B.Hallway","","room","corr"),
       ("Blue Stairs","蓝楼梯","Blue Stairs","","room","corr"),("Garage Stairs","车库楼梯","Garage Stairs","","room","corr"),
       ("Main Stairs","主楼梯","Main Stairs","","room","corr"),("CarGarageEntrance","车库入口","Car Garage Ent.","","room","corr")],
  "1":[("Gaming","游戏室","Gaming","目标","obj","gold"),("Bar","吧台","Bar","目标","obj","gold"),
       ("Dining","餐厅","Dining","目标","obj","gold"),("Kitchen","厨房","Kitchen","目标","obj","gold"),
       ("Bar Stock","吧台储藏","Bar Stock","","room","room"),("Fireplace","壁炉厅","Fireplace","","room","room"),
       ("Mudroom","玄关","Mudroom","","room","room"),("Trophy","奖杯室","Trophy","","room","room"),
       ("Main","主厅","Main","","room","room"),("Dining Hallway","餐厅走廊","Dining Hall","","room","corr"),
       ("Kitchen Hallway","厨房走廊","Kitchen Hall","","room","corr"),("Bar Hallway","吧台走廊","Bar Hall","","room","corr"),
       ("Gaming Hallway","游戏室走廊","Gaming Hall","","room","corr"),("Fireplace Stairs","壁炉楼梯","Fireplace Stairs","","room","corr"),
       ("Trophy Stairs","奖杯楼梯","Trophy Stairs","","room","corr"),("Backyard Stairs","后院楼梯","Backyard Stairs","","room","corr")],
  "2":[("Master","主卧","Master","目标","obj","gold"),("Office","办公室","Office","目标","obj","gold"),
       ("Piano","钢琴室","Piano","","room","room"),("Solarium","阳光房","Solarium","","room","room"),
       ("Bathroom","洗手间","Bathroom","","room","room"),("Closet","壁橱","Closet","","room","room"),
       ("Mezzanine","夹层","Mezzanine","","room","room"),("Library","图书室","Library","","room","room"),
       ("Library Entrance","图书室入口","Library Ent.","","room","corr"),("Library Hallway","图书室走廊","Library Hall","","room","corr"),
       ("Trophy Stairs","奖杯楼梯","Trophy Stairs","","room","corr")],
  "3":[("Roof","屋顶","Roof","室外","ext","ext"),("Backyard","后院","Backyard","室外","ext","ext")],
 },
}

MAPCFG["labs"] = {
 "mapcn":"实验室","mapen":"Nighthaven Labs",
 "order":["3","2","1","0"], "default":"1",
 "names":{"3":"屋顶","2":"二楼","1":"一楼","0":"地下室"},
 "en":{"3":"ROOF","2":"2F","1":"1F","0":"B"},
 "notes":{"3":"屋顶层 · 直升机坪","2":"指挥室 + 服务器 + 会议室","1":"厨房 + 食堂 + 控制室 + 储藏","0":"外骨骼室 + 装配室 + 纳米室"},
 "sites":[{"id":"1","f":"2","n":"① 指挥·服务器"},{"id":"2","f":"1","n":"② 厨房·食堂"},
          {"id":"3","f":"1","n":"③ 控制室·储藏"},{"id":"4","f":"0","n":"④ 外骨骼·装配"}],
 "bombs":{"2":["1A","1B"],"1":["2A","2B","3A","3B"],"0":["4A","4B"]},
 "rooms":{
  "0":[("Exo","外骨骼室","Exo","目标","obj","gold"),("Animus","阿尼姆斯","Animus","目标","obj","gold"),
       ("Assembly","装配室","Assembly","","room","room"),("Nano","纳米室","Nano","","room","room"),
       ("Tank","罐体室","Tank","","room","room"),("Cargo","货舱","Cargo","","room","room"),
       ("Emergency","应急室","Emergency","","room","room"),("AssemblyDelivery","装配送货","Assembly Del.","","room","room"),
       ("AnimusDelivery","阿尼姆斯送货","Animus Del.","","room","room"),("Nano Hallway","纳米走廊","Nano Hall","","room","corr"),
       ("Exo Hallway","外骨骼走廊","Exo Hall","","room","corr"),("Cargo Stairs","货舱楼梯","Cargo Stairs","","room","corr"),
       ("VendingStairs","售货楼梯","Vending Stairs","","room","corr")],
  "1":[("Kitchen","厨房","Kitchen","目标","obj","gold"),("Cafeteria","食堂","Cafeteria","目标","obj","gold"),
       ("Control","控制室","Control","目标","obj","gold"),("Storage","储藏室","Storage","目标","obj","gold"),
       ("Gaming","游戏室","Gaming","","room","room"),("Warehouse","仓库","Warehouse","","room","room"),
       ("Vending","售货区","Vending","","room","room"),("Pantry","储物间","Pantry","","room","room"),
       ("Lobby","大堂","Lobby","","room","room"),("Containers","集装箱","Containers","","room","room"),
       ("Delivery","送货区","Delivery","","room","room"),("Control Hallway","控制室走廊","Control Hall","","room","corr"),
       ("Cafeteria Hallway","食堂走廊","Cafeteria Hall","","room","corr"),("Gaming Hallway","游戏室走廊","Gaming Hall","","room","corr"),
       ("Lobby Hallway","大堂走廊","Lobby Hall","","room","corr"),("StorageHallway","储藏走廊","Storage Hall","","room","corr"),
       ("WarehouseEntrance","仓库入口","Warehouse Ent.","","room","corr"),("West Stairs","西楼梯","West Stairs","","room","corr"),
       ("Blue Stairs","蓝楼梯","Blue Stairs","","room","corr")],
  "2":[("Command","指挥室","Command","目标","obj","gold"),("Server","服务器室","Server","目标","obj","gold"),
       ("Meeting","会议室","Meeting","","room","room"),("Lobby","大堂","Lobby","","room","room"),
       ("Connector","连接厅","Connector","","room","room"),("Electrical","电气室","Electrical","","room","room"),
       ("IT","IT室","IT","","room","room"),("Warehouse","仓库","Warehouse","","room","room"),
       ("Observatory","观测台","Observatory","","room","room"),("Top Lobby","大堂上层","Top Lobby","","room","room"),
       ("Command Hallway","指挥走廊","Command Hall","","room","corr"),("Meeting Hallway","会议走廊","Meeting Hall","","room","corr"),
       ("West Stairs","西楼梯","West Stairs","","room","corr"),("Blue Stairs","蓝楼梯","Blue Stairs","","room","corr"),
       ("Catwalk","猫道","Catwalk","","room","corr"),("Containers","集装箱","Containers","","room","room"),
       ("Delivery","送货区","Delivery","","room","room")],
  "3":[("Helipad","直升机坪","Helipad","室外","ext","ext"),("Park","停车场","Park","室外","ext","ext")],
 },
}
